//=============================================================================
// axi_crossbar.v — AXI4 Crossbar (M=6, S=2, round-robin arbitration)
// CaduceusCore SoC Phase 3-4 / Task 7
//
// Masters (M=6): Ibex(0) / MXU(1) / SFU(2) / Vector(3) / DMA(4) / PCIe(5)
// Slaves  (S=2): SRAM(0) / DRAM(1)
//
// Features:
//   - Full AXI4 5-channel (AW/W/B/AR/R) crossbar
//   - Address-based routing:
//       SRAM: 0x2000_0000 ~ 0x203F_FFFF  → slave 0
//       DRAM: 0x8000_0000 ~ 0xFFFF_FFFF  → slave 1
//       Other addresses                   → DECERR (generated by crossbar)
//   - Round-robin arbitration per slave; AW and AR arbitrated independently
//   - AXI ID preservation: slave-side ID = {master_sel[2:0], axi_id[5:0]}
//     Response routing decodes master_sel from BID/RID to return to correct master
//   - Single outstanding transaction per master per direction
//   - DECERR injection for unmapped addresses (absorbs W beats, generates B/R)
//
// Parameters:
//   DATA_WIDTH  = 512   (data bus width in bits)
//   ADDR_WIDTH  = 32    (address bus width)
//   M_ID_WIDTH  = 6     (per-master AXI ID width)
//   MSEL_WIDTH  = 3     (log2(NUM_M))
//   NUM_M       = 6     (number of master ports)
//   NUM_S       = 2     (number of slave ports)
//
// References: AMBA AXI4 spec, CaduceusCore/rtl/soc/sram_ctrl.v
//=============================================================================

module axi_crossbar #(
    parameter int unsigned DATA_WIDTH  = 512,
    parameter int unsigned ADDR_WIDTH  = 32,
    parameter int unsigned M_ID_WIDTH  = 6,
    parameter int unsigned MSEL_WIDTH  = 3,
    parameter int unsigned NUM_M       = 6,
    parameter int unsigned NUM_S       = 2,
    parameter int unsigned S_ID_WIDTH  = M_ID_WIDTH + MSEL_WIDTH  // derived
) (
    input  wire                                 clk,
    input  wire                                 rst_n,

    // ── Master ports (M=6) — AXI4 slave interfaces facing masters ──────────
    input  wire [NUM_M-1:0][M_ID_WIDTH-1:0]     m_awid_i,
    input  wire [NUM_M-1:0][ADDR_WIDTH-1:0]     m_awaddr_i,
    input  wire [NUM_M-1:0][7:0]                m_awlen_i,
    input  wire [NUM_M-1:0][2:0]                m_awsize_i,
    input  wire [NUM_M-1:0][1:0]                m_awburst_i,
    input  wire [NUM_M-1:0]                     m_awvalid_i,
    output wire [NUM_M-1:0]                     m_awready_o,

    input  wire [NUM_M-1:0][DATA_WIDTH-1:0]     m_wdata_i,
    input  wire [NUM_M-1:0][DATA_WIDTH/8-1:0]   m_wstrb_i,
    input  wire [NUM_M-1:0]                     m_wlast_i,
    input  wire [NUM_M-1:0]                     m_wvalid_i,
    output wire [NUM_M-1:0]                     m_wready_o,

    output wire [NUM_M-1:0][M_ID_WIDTH-1:0]     m_bid_o,
    output wire [NUM_M-1:0][1:0]                m_bresp_o,
    output wire [NUM_M-1:0]                     m_bvalid_o,
    input  wire [NUM_M-1:0]                     m_bready_i,

    input  wire [NUM_M-1:0][M_ID_WIDTH-1:0]     m_arid_i,
    input  wire [NUM_M-1:0][ADDR_WIDTH-1:0]     m_araddr_i,
    input  wire [NUM_M-1:0][7:0]                m_arlen_i,
    input  wire [NUM_M-1:0][2:0]                m_arsize_i,
    input  wire [NUM_M-1:0][1:0]                m_arburst_i,
    input  wire [NUM_M-1:0]                     m_arvalid_i,
    output wire [NUM_M-1:0]                     m_arready_o,

    output wire [NUM_M-1:0][M_ID_WIDTH-1:0]     m_rid_o,
    output wire [NUM_M-1:0][DATA_WIDTH-1:0]     m_rdata_o,
    output wire [NUM_M-1:0][1:0]                m_rresp_o,
    output wire [NUM_M-1:0]                     m_rlast_o,
    output wire [NUM_M-1:0]                     m_rvalid_o,
    input  wire [NUM_M-1:0]                     m_rready_i,

    // ── Slave ports (S=2) — AXI4 master interfaces facing slaves ────────────
    output wire [NUM_S-1:0][S_ID_WIDTH-1:0]     s_awid_o,
    output wire [NUM_S-1:0][ADDR_WIDTH-1:0]     s_awaddr_o,
    output wire [NUM_S-1:0][7:0]                s_awlen_o,
    output wire [NUM_S-1:0][2:0]                s_awsize_o,
    output wire [NUM_S-1:0][1:0]                s_awburst_o,
    output wire [NUM_S-1:0]                     s_awvalid_o,
    input  wire [NUM_S-1:0]                     s_awready_i,

    output wire [NUM_S-1:0][DATA_WIDTH-1:0]     s_wdata_o,
    output wire [NUM_S-1:0][DATA_WIDTH/8-1:0]   s_wstrb_o,
    output wire [NUM_S-1:0]                     s_wlast_o,
    output wire [NUM_S-1:0]                     s_wvalid_o,
    input  wire [NUM_S-1:0]                     s_wready_i,

    input  wire [NUM_S-1:0][S_ID_WIDTH-1:0]     s_bid_i,
    input  wire [NUM_S-1:0][1:0]                s_bresp_i,
    input  wire [NUM_S-1:0]                     s_bvalid_i,
    output wire [NUM_S-1:0]                     s_bready_o,

    output wire [NUM_S-1:0][S_ID_WIDTH-1:0]     s_arid_o,
    output wire [NUM_S-1:0][ADDR_WIDTH-1:0]     s_araddr_o,
    output wire [NUM_S-1:0][7:0]                s_arlen_o,
    output wire [NUM_S-1:0][2:0]                s_arsize_o,
    output wire [NUM_S-1:0][1:0]                s_arburst_o,
    output wire [NUM_S-1:0]                     s_arvalid_o,
    input  wire [NUM_S-1:0]                     s_arready_i,

    input  wire [NUM_S-1:0][S_ID_WIDTH-1:0]     s_rid_i,
    input  wire [NUM_S-1:0][DATA_WIDTH-1:0]     s_rdata_i,
    input  wire [NUM_S-1:0][1:0]                s_rresp_i,
    input  wire [NUM_S-1:0]                     s_rlast_i,
    input  wire [NUM_S-1:0]                     s_rvalid_i,
    output wire [NUM_S-1:0]                     s_rready_o
);

    // =========================================================================
    // Address decode
    // =========================================================================
    // Returns {1'b1, zeros} for DECERR; {1'b0, slave_idx} for hit.
    function automatic logic [MSEL_WIDTH:0] decode_slave(
        input [ADDR_WIDTH-1:0] addr
    );
        // SRAM: 0x2000_0000 ~ 0x203F_FFFF
        if ((addr[31:22] == 10'b0010000000) && (addr[21:0] <= 22'h3F_FFFF))
            decode_slave = {1'b0, 3'd0};  // slave 0
        // DRAM: 0x8000_0000 ~ 0xFFFF_FFFF
        else if (addr[31])
            decode_slave = {1'b0, 3'd1};  // slave 1
        else
            decode_slave = {1'b1, 3'd0};  // DECERR
    endfunction

    // =========================================================================
    // Combinational decode wires (per master)
    // =========================================================================
    wire [NUM_M-1:0][MSEL_WIDTH:0]   m_aw_dec;
    wire [NUM_M-1:0][MSEL_WIDTH:0]   m_ar_dec;
    wire [NUM_M-1:0]                 m_aw_hit;
    wire [NUM_M-1:0]                 m_ar_hit;
    wire [NUM_M-1:0][MSEL_WIDTH-1:0] m_aw_slave;
    wire [NUM_M-1:0][MSEL_WIDTH-1:0] m_ar_slave;

    genvar gmi;
    genvar gsi;
    generate
        for (gmi = 0; gmi < NUM_M; gmi = gmi + 1) begin : gen_decode
            assign m_aw_dec[gmi]   = decode_slave(m_awaddr_i[gmi]);
            assign m_ar_dec[gmi]   = decode_slave(m_araddr_i[gmi]);
            assign m_aw_hit[gmi]   = !m_aw_dec[gmi][MSEL_WIDTH];
            assign m_ar_hit[gmi]   = !m_ar_dec[gmi][MSEL_WIDTH];
            assign m_aw_slave[gmi] = m_aw_dec[gmi][MSEL_WIDTH-1:0];
            assign m_ar_slave[gmi] = m_ar_dec[gmi][MSEL_WIDTH-1:0];
        end
    endgenerate

    // =========================================================================
    // Per-master transaction state
    // =========================================================================
    reg [NUM_M-1:0]                     m_aw_active;
    reg [NUM_M-1:0][MSEL_WIDTH:0]       m_aw_tgt;
    reg [NUM_M-1:0][M_ID_WIDTH-1:0]     m_aw_id_stored;
    reg [NUM_M-1:0][7:0]                m_aw_len_stored;
    reg [NUM_M-1:0][7:0]                m_w_beat;
    reg [NUM_M-1:0]                     m_w_last;

    reg [NUM_M-1:0]                     m_ar_active;
    reg [NUM_M-1:0][MSEL_WIDTH:0]       m_ar_tgt;
    reg [NUM_M-1:0][M_ID_WIDTH-1:0]     m_ar_id_stored;
    reg [NUM_M-1:0][7:0]                m_ar_len_stored;
    reg [NUM_M-1:0][7:0]                m_r_beat;

    // =========================================================================
    // Per-slave arbitration state
    // =========================================================================
    reg [NUM_S-1:0]                     aw_busy;
    reg [NUM_S-1:0][MSEL_WIDTH-1:0]     aw_granted;
    reg [NUM_S-1:0][MSEL_WIDTH-1:0]     aw_priority;

    reg [NUM_S-1:0]                     ar_busy;
    reg [NUM_S-1:0][MSEL_WIDTH-1:0]     ar_granted;
    reg [NUM_S-1:0][MSEL_WIDTH-1:0]     ar_priority;

    // =========================================================================
    // Latched AW/AR data per slave (captured when grant is made)
    // =========================================================================
    reg [NUM_S-1:0][S_ID_WIDTH-1:0]     s_awid_latched;
    reg [NUM_S-1:0][ADDR_WIDTH-1:0]     s_awaddr_latched;
    reg [NUM_S-1:0][7:0]                s_awlen_latched;
    reg [NUM_S-1:0][2:0]                s_awsize_latched;
    reg [NUM_S-1:0][1:0]                s_awburst_latched;
    reg [NUM_S-1:0]                     s_awvalid_latched;
    reg [NUM_S-1:0]                     aw_latch_clr;     // 2-cycle clear pending

    reg [NUM_S-1:0][S_ID_WIDTH-1:0]     s_arid_latched;
    reg [NUM_S-1:0][ADDR_WIDTH-1:0]     s_araddr_latched;
    reg [NUM_S-1:0][7:0]                s_arlen_latched;
    reg [NUM_S-1:0][2:0]                s_arsize_latched;
    reg [NUM_S-1:0][1:0]                s_arburst_latched;
    reg [NUM_S-1:0]                     s_arvalid_latched;
    reg [NUM_S-1:0]                     ar_latch_clr;     // 2-cycle clear pending

    // =========================================================================
    // AW channel — master ready
    // =========================================================================
    // AWREADY: accept if master not active AND (DECERR OR target slave free)
    generate
        for (gmi = 0; gmi < NUM_M; gmi = gmi + 1) begin : gen_aw_ready
            assign m_awready_o[gmi] = !m_aw_active[gmi] &&
                (!m_aw_hit[gmi] || !aw_busy[m_aw_slave[gmi]]);
        end
    endgenerate

    // AW handshake detect
    wire [NUM_M-1:0] m_aw_accept;
    generate
        for (gmi = 0; gmi < NUM_M; gmi = gmi + 1) begin : gen_aw_acc
            assign m_aw_accept[gmi] = m_awvalid_i[gmi] && m_awready_o[gmi];
        end
    endgenerate

    // =========================================================================
    // Slave AW outputs — driven from latched data
    // =========================================================================
    generate
        for (gsi = 0; gsi < NUM_S; gsi = gsi + 1) begin : gen_aw_latch_out
            assign s_awid_o[gsi]    = s_awid_latched[gsi];
            assign s_awaddr_o[gsi]  = s_awaddr_latched[gsi];
            assign s_awlen_o[gsi]   = s_awlen_latched[gsi];
            assign s_awsize_o[gsi]  = s_awsize_latched[gsi];
            assign s_awburst_o[gsi] = s_awburst_latched[gsi];
            assign s_awvalid_o[gsi] = s_awvalid_latched[gsi];
        end
    endgenerate

    // =========================================================================
    // W channel routing
    // =========================================================================
    wire [NUM_S-1:0][MSEL_WIDTH-1:0] w_src;
    generate
        for (gsi = 0; gsi < NUM_S; gsi = gsi + 1) begin : gen_w_mux
            assign w_src[gsi] = aw_granted[gsi];
            assign s_wdata_o[gsi]  = m_wdata_i[w_src[gsi]];
            assign s_wstrb_o[gsi]  = m_wstrb_i[w_src[gsi]];
            assign s_wlast_o[gsi]  = m_wlast_i[w_src[gsi]];
            assign s_wvalid_o[gsi] = aw_busy[gsi] && m_wvalid_i[w_src[gsi]];
        end
    endgenerate

    // Master WREADY: DECERR → always ready; normal → slave's WREADY
    generate
        for (gmi = 0; gmi < NUM_M; gmi = gmi + 1) begin : gen_w_ready
            wire is_dec  = m_aw_active[gmi] && m_aw_tgt[gmi][MSEL_WIDTH];
            wire is_norm = m_aw_active[gmi] && !m_aw_tgt[gmi][MSEL_WIDTH];
            wire [MSEL_WIDTH-1:0] tgt = m_aw_tgt[gmi][MSEL_WIDTH-1:0];
            assign m_wready_o[gmi] = is_dec  ? 1'b1 :
                                     is_norm ? s_wready_i[tgt] :
                                     1'b0;
        end
    endgenerate

    // =========================================================================
    // B channel routing (slave → master)
    // =========================================================================
    // Slave BID = {master_sel, axi_id}. Crossbar strips master_sel on return.
    generate
        for (gsi = 0; gsi < NUM_S; gsi = gsi + 1) begin : gen_b_slvready
            wire [MSEL_WIDTH-1:0] b_m = s_bid_i[gsi][S_ID_WIDTH-1 : M_ID_WIDTH];
            assign s_bready_o[gsi] = aw_busy[gsi] && m_bready_i[b_m];
        end
    endgenerate

    generate
        for (gmi = 0; gmi < NUM_M; gmi = gmi + 1) begin : gen_b_mst

            // B from slave 0 matching this master
            wire b0 = s_bvalid_i[0] &&
                (s_bid_i[0][S_ID_WIDTH-1 : M_ID_WIDTH] == gmi[MSEL_WIDTH-1:0]) &&
                aw_busy[0] && (aw_granted[0] == gmi[MSEL_WIDTH-1:0]);

            // B from slave 1 matching this master
            wire b1 = s_bvalid_i[1] &&
                (s_bid_i[1][S_ID_WIDTH-1 : M_ID_WIDTH] == gmi[MSEL_WIDTH-1:0]) &&
                aw_busy[1] && (aw_granted[1] == gmi[MSEL_WIDTH-1:0]);

            wire b_slv = b0 || b1;

            // DECERR write: generate B after WLAST seen
            wire b_dec = m_aw_active[gmi] && m_aw_tgt[gmi][MSEL_WIDTH] && m_w_last[gmi];

            wire [M_ID_WIDTH-1:0] b_id_slv;
            assign b_id_slv = b0 ? s_bid_i[0][M_ID_WIDTH-1:0] :
                              b1 ? s_bid_i[1][M_ID_WIDTH-1:0] : '0;

            wire [1:0] b_resp_slv;
            assign b_resp_slv = b0 ? s_bresp_i[0] : b1 ? s_bresp_i[1] : 2'b00;

            assign m_bid_o[gmi]   = b_slv ? b_id_slv : m_aw_id_stored[gmi];
            assign m_bresp_o[gmi] = b_slv ? b_resp_slv : 2'b11;   // DECERR
            assign m_bvalid_o[gmi] = b_slv || b_dec;
        end
    endgenerate

    // =========================================================================
    // AR channel — master ready + slave mux
    // =========================================================================
    generate
        for (gmi = 0; gmi < NUM_M; gmi = gmi + 1) begin : gen_ar_ready
            assign m_arready_o[gmi] = !m_ar_active[gmi] &&
                (!m_ar_hit[gmi] || !ar_busy[m_ar_slave[gmi]]);
        end
    endgenerate

    wire [NUM_M-1:0] m_ar_accept;
    generate
        for (gmi = 0; gmi < NUM_M; gmi = gmi + 1) begin : gen_ar_acc
            assign m_ar_accept[gmi] = m_arvalid_i[gmi] && m_arready_o[gmi];
        end
    endgenerate

    // =========================================================================
    // Slave AR outputs — driven from latched data
    // =========================================================================
    generate
        for (gsi = 0; gsi < NUM_S; gsi = gsi + 1) begin : gen_ar_latch_out
            assign s_arid_o[gsi]    = s_arid_latched[gsi];
            assign s_araddr_o[gsi]  = s_araddr_latched[gsi];
            assign s_arlen_o[gsi]   = s_arlen_latched[gsi];
            assign s_arsize_o[gsi]  = s_arsize_latched[gsi];
            assign s_arburst_o[gsi] = s_arburst_latched[gsi];
            assign s_arvalid_o[gsi] = s_arvalid_latched[gsi];
        end
    endgenerate

    // =========================================================================
    // R channel routing (slave → master)
    // =========================================================================
    generate
        for (gsi = 0; gsi < NUM_S; gsi = gsi + 1) begin : gen_r_slvready
            wire [MSEL_WIDTH-1:0] r_m = s_rid_i[gsi][S_ID_WIDTH-1 : M_ID_WIDTH];
            assign s_rready_o[gsi] = ar_busy[gsi] && m_rready_i[r_m];
        end
    endgenerate

    generate
        for (gmi = 0; gmi < NUM_M; gmi = gmi + 1) begin : gen_r_mst

            // R from slave 0 matching this master
            wire r0 = s_rvalid_i[0] &&
                (s_rid_i[0][S_ID_WIDTH-1 : M_ID_WIDTH] == gmi[MSEL_WIDTH-1:0]) &&
                ar_busy[0] && (ar_granted[0] == gmi[MSEL_WIDTH-1:0]);

            // R from slave 1 matching this master
            wire r1 = s_rvalid_i[1] &&
                (s_rid_i[1][S_ID_WIDTH-1 : M_ID_WIDTH] == gmi[MSEL_WIDTH-1:0]) &&
                ar_busy[1] && (ar_granted[1] == gmi[MSEL_WIDTH-1:0]);

            wire r_slv = r0 || r1;

            // DECERR read: generate R beats
            wire r_dec = m_ar_active[gmi] && m_ar_tgt[gmi][MSEL_WIDTH];
            wire r_dec_beat = r_dec && (m_r_beat[gmi] <= m_ar_len_stored[gmi]);

            wire [M_ID_WIDTH-1:0] r_id_slv;
            assign r_id_slv = r0 ? s_rid_i[0][M_ID_WIDTH-1:0] :
                              r1 ? s_rid_i[1][M_ID_WIDTH-1:0] : '0;

            wire [DATA_WIDTH-1:0] r_data_slv;
            assign r_data_slv = r0 ? s_rdata_i[0] : r1 ? s_rdata_i[1] : '0;

            wire [1:0] r_resp_slv;
            assign r_resp_slv = r0 ? s_rresp_i[0] : r1 ? s_rresp_i[1] : 2'b00;

            wire r_last_slv;
            assign r_last_slv = r0 ? s_rlast_i[0] : r1 ? s_rlast_i[1] : 1'b0;

            assign m_rid_o[gmi]   = r_slv ? r_id_slv  : m_ar_id_stored[gmi];
            assign m_rdata_o[gmi] = r_slv ? r_data_slv : {DATA_WIDTH{1'b0}};
            assign m_rresp_o[gmi] = r_slv ? r_resp_slv : 2'b11;
            assign m_rlast_o[gmi] = r_slv ? r_last_slv :
                                    r_dec_beat ? (m_r_beat[gmi] >= m_ar_len_stored[gmi]) : 1'b0;
            assign m_rvalid_o[gmi] = r_slv || r_dec_beat;
        end
    endgenerate

    // =========================================================================
    // Temporary variables for procedural round-robin computation
    // =========================================================================
    integer               mi_s, si_s;
    integer               ak_s, rk_s;
    reg [MSEL_WIDTH-1:0]  gnt_val;
    reg                   rr_found;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            for (mi_s = 0; mi_s < NUM_M; mi_s = mi_s + 1) begin
                m_aw_active[mi_s]     <= 1'b0;
                m_aw_tgt[mi_s]        <= '0;
                m_aw_id_stored[mi_s]  <= '0;
                m_aw_len_stored[mi_s] <= '0;
                m_w_beat[mi_s]        <= '0;
                m_w_last[mi_s]        <= 1'b0;
                m_ar_active[mi_s]     <= 1'b0;
                m_ar_tgt[mi_s]        <= '0;
                m_ar_id_stored[mi_s]  <= '0;
                m_ar_len_stored[mi_s] <= '0;
                m_r_beat[mi_s]        <= '0;
            end
            for (si_s = 0; si_s < NUM_S; si_s = si_s + 1) begin
                aw_busy[si_s]           <= 1'b0;
                aw_granted[si_s]        <= '0;
                aw_priority[si_s]       <= '0;
                s_awvalid_latched[si_s] <= 1'b0;
                aw_latch_clr[si_s]      <= 1'b0;
                ar_busy[si_s]           <= 1'b0;
                ar_granted[si_s]        <= '0;
                ar_priority[si_s]       <= '0;
                s_arvalid_latched[si_s] <= 1'b0;
                ar_latch_clr[si_s]      <= 1'b0;
            end
        end else begin
            // =================================================================
            // MASTER STATE: AW acceptance, W counting, B clearing
            // =================================================================
            for (mi_s = 0; mi_s < NUM_M; mi_s = mi_s + 1) begin
                // AW accept
                if (m_aw_accept[mi_s] && !m_aw_active[mi_s]) begin
                    m_aw_active[mi_s]     <= 1'b1;
                    m_aw_tgt[mi_s]        <= m_aw_dec[mi_s];
                    m_aw_id_stored[mi_s]  <= m_awid_i[mi_s];
                    m_aw_len_stored[mi_s] <= m_awlen_i[mi_s];
                    m_w_beat[mi_s]        <= '0;
                    m_w_last[mi_s]        <= 1'b0;
                end

                // W beat counting
                if (m_aw_active[mi_s] && m_wvalid_i[mi_s] && m_wready_o[mi_s]) begin
                    m_w_beat[mi_s] <= m_w_beat[mi_s] + 1;
                    if (m_wlast_i[mi_s])
                        m_w_last[mi_s] <= 1'b1;
                end

                // B handshake completes write
                if (m_aw_active[mi_s] && m_bvalid_o[mi_s] && m_bready_i[mi_s]) begin
                    m_aw_active[mi_s] <= 1'b0;
                    m_aw_tgt[mi_s]    <= '0;
                    m_w_beat[mi_s]    <= '0;
                    m_w_last[mi_s]    <= 1'b0;
                end
            end

            // =================================================================
            // MASTER STATE: AR acceptance, R counting, R clearing
            // =================================================================
            for (mi_s = 0; mi_s < NUM_M; mi_s = mi_s + 1) begin
                // AR accept
                if (m_ar_accept[mi_s] && !m_ar_active[mi_s]) begin
                    m_ar_active[mi_s]     <= 1'b1;
                    m_ar_tgt[mi_s]        <= m_ar_dec[mi_s];
                    m_ar_id_stored[mi_s]  <= m_arid_i[mi_s];
                    m_ar_len_stored[mi_s] <= m_arlen_i[mi_s];
                    m_r_beat[mi_s]        <= '0;
                end

                // R beat counting
                if (m_ar_active[mi_s] && m_rvalid_o[mi_s] && m_rready_i[mi_s]) begin
                    m_r_beat[mi_s] <= m_r_beat[mi_s] + 1;
                end

                // R completion (last beat)
                if (m_ar_active[mi_s] && m_rvalid_o[mi_s] && m_rready_i[mi_s] && m_rlast_o[mi_s]) begin
                    m_ar_active[mi_s] <= 1'b0;
                    m_ar_tgt[mi_s]    <= '0;
                    m_r_beat[mi_s]    <= '0;
                end
            end

            // =================================================================
            // SLAVE AW ARBITRATION: round-robin grant + 2-cycle latch clear
            // =================================================================
            for (si_s = 0; si_s < NUM_S; si_s = si_s + 1) begin
                // Phase 2: clear latch (one cycle after handshake detected)
                if (aw_latch_clr[si_s]) begin
                    s_awvalid_latched[si_s] <= 1'b0;
                    aw_latch_clr[si_s]      <= 1'b0;
                end

                // Phase 1: detect AW handshake with slave, set clear flag
                if (s_awvalid_latched[si_s] && s_awready_i[si_s] && !aw_latch_clr[si_s]) begin
                    aw_latch_clr[si_s] <= 1'b1;
                end

                // Find next AW grant when slave is free and latch is clear
                if (!aw_busy[si_s] && !s_awvalid_latched[si_s] && !aw_latch_clr[si_s]) begin
                    gnt_val = '0;
                    rr_found = 1'b0;

                    for (ak_s = 0; ak_s < NUM_M && !rr_found; ak_s = ak_s + 1) begin
                        gnt_val = (aw_priority[si_s] + 1 + ak_s) % NUM_M;
                        if (m_awvalid_i[gnt_val] && m_aw_hit[gnt_val] &&
                            (m_aw_slave[gnt_val] == si_s[MSEL_WIDTH-1:0]) &&
                            !m_aw_active[gnt_val]) begin
                            rr_found = 1'b1;
                        end
                    end

                    if (rr_found && m_awvalid_i[gnt_val] && m_awready_o[gnt_val]) begin
                        // Grant: latch AW data and mark slave busy
                        s_awid_latched[si_s]    <= {gnt_val, m_awid_i[gnt_val]};
                        s_awaddr_latched[si_s]  <= m_awaddr_i[gnt_val];
                        s_awlen_latched[si_s]   <= m_awlen_i[gnt_val];
                        s_awsize_latched[si_s]  <= m_awsize_i[gnt_val];
                        s_awburst_latched[si_s] <= m_awburst_i[gnt_val];
                        s_awvalid_latched[si_s] <= 1'b1;
                        aw_busy[si_s]           <= 1'b1;
                        aw_granted[si_s]        <= gnt_val;
                        aw_priority[si_s]       <= gnt_val;
                    end
                end

                // Release AW grant on B handshake
                if (aw_busy[si_s]) begin
                    if (m_bvalid_o[aw_granted[si_s]] && m_bready_i[aw_granted[si_s]])
                        aw_busy[si_s] <= 1'b0;
                end
            end

            // =================================================================
            // SLAVE AR ARBITRATION: round-robin grant + 2-cycle latch clear
            // =================================================================
            for (si_s = 0; si_s < NUM_S; si_s = si_s + 1) begin
                // Phase 2: clear latch
                if (ar_latch_clr[si_s]) begin
                    s_arvalid_latched[si_s] <= 1'b0;
                    ar_latch_clr[si_s]      <= 1'b0;
                end

                // Phase 1: detect AR handshake
                if (s_arvalid_latched[si_s] && s_arready_i[si_s] && !ar_latch_clr[si_s]) begin
                    ar_latch_clr[si_s] <= 1'b1;
                end

                // Find next AR grant when slave is free and latch is clear
                if (!ar_busy[si_s] && !s_arvalid_latched[si_s] && !ar_latch_clr[si_s]) begin
                    gnt_val = '0;
                    rr_found = 1'b0;

                    for (rk_s = 0; rk_s < NUM_M && !rr_found; rk_s = rk_s + 1) begin
                        gnt_val = (ar_priority[si_s] + 1 + rk_s) % NUM_M;
                        if (m_arvalid_i[gnt_val] && m_ar_hit[gnt_val] &&
                            (m_ar_slave[gnt_val] == si_s[MSEL_WIDTH-1:0]) &&
                            !m_ar_active[gnt_val]) begin
                            rr_found = 1'b1;
                        end
                    end

                    if (rr_found && m_arvalid_i[gnt_val] && m_arready_o[gnt_val]) begin
                        // Grant: latch AR data and mark slave busy
                        s_arid_latched[si_s]    <= {gnt_val, m_arid_i[gnt_val]};
                        s_araddr_latched[si_s]  <= m_araddr_i[gnt_val];
                        s_arlen_latched[si_s]   <= m_arlen_i[gnt_val];
                        s_arsize_latched[si_s]  <= m_arsize_i[gnt_val];
                        s_arburst_latched[si_s] <= m_arburst_i[gnt_val];
                        s_arvalid_latched[si_s] <= 1'b1;
                        ar_busy[si_s]           <= 1'b1;
                        ar_granted[si_s]        <= gnt_val;
                        ar_priority[si_s]       <= gnt_val;
                    end
                end

                // Release AR grant on R completion
                if (ar_busy[si_s]) begin
                    if (m_rvalid_o[ar_granted[si_s]] && m_rready_i[ar_granted[si_s]] &&
                        m_rlast_o[ar_granted[si_s]])
                        ar_busy[si_s] <= 1'b0;
                end
            end
        end
    end

endmodule
