"""CaduceusCore production command IR package."""

from .command_ir import CommandBlob, load_manifest
from .command_ir_types import (
    CAD_BLOB_MAJOR,
    CAD_BLOB_MINOR,
    CAD_BLOB_MAGIC,
    CAD_CAP_DMA,
    CAD_CAP_MXU,
    CAD_CAP_PCIE,
    CAD_CAP_SFU,
    CAD_CAP_VECTOR,
    CAD_CMD_ENTRY_BYTES,
    CAD_DESC_BYTES,
    CAD_MAX_BUFFERS,
    CAD_MAX_COMMANDS,
    CAD_MAX_DEPS,
    CAD_OP_MMUL,
    DRAM_BASE,
    DRAM_SIZE,
    HEADER_SIZE,
    SRAM_BASE,
    SRAM_SIZE,
    TILE_H,
    TILE_W,
    LowerStatus,
)

__all__ = [
    "CommandBlob",
    "LowerStatus",
    "load_manifest",
    "CAD_BLOB_MAJOR",
    "CAD_BLOB_MINOR",
    "CAD_BLOB_MAGIC",
    "CAD_CAP_DMA",
    "CAD_CAP_MXU",
    "CAD_CAP_PCIE",
    "CAD_CAP_SFU",
    "CAD_CAP_VECTOR",
    "CAD_CMD_ENTRY_BYTES",
    "CAD_DESC_BYTES",
    "CAD_MAX_BUFFERS",
    "CAD_MAX_COMMANDS",
    "CAD_MAX_DEPS",
    "CAD_OP_MMUL",
    "DRAM_BASE",
    "DRAM_SIZE",
    "HEADER_SIZE",
    "SRAM_BASE",
    "SRAM_SIZE",
    "TILE_H",
    "TILE_W",
]
