//=============================================================================
// tb_mxu — Self-Checking MXU Top-Level Testbench
//=============================================================================
// Reads $readmemh test vectors generated by gen_mxu_vectors.py, drives mxu_top
// through MMIO, feeds weight/activation broadcast buses during compute, captures
// store_out results, writes $writememh output, and compares with golden_output.hex.
//
// Usage:
//   vcs -full64 -sverilog -timescale=1ns/1ps -top tb_mxu \
//       CaduceusCore/rtl/tb/tb_mxu.v CaduceusCore/rtl/mxu/*.v -l tb_compile.log
//   ./simv_mxu +testdir=CaduceusCore/rtl/test_vectors/mxu/single_tile -l sim.log
//
// Dependencies: Task 8 (test vectors from gen_mxu_vectors.py).
//=============================================================================

`timescale 1ns / 1ps

module tb_mxu;

    //=========================================================================
    // Parameters
    //=========================================================================
    localparam CLK_HALF  = 5;                 // 5ns half-period → 100 MHz
    localparam MAX_DIM      = 2048;           // max supported dimension (M/K/N)
    localparam MAX_W_WORDS  = ((MAX_DIM * MAX_DIM) + 7) / 8; // ceil(MAX_DIM^2/8) INT4 packed
    localparam MAX_A_WORDS  = ((MAX_DIM * MAX_DIM) + 3) / 4; // ceil(MAX_DIM^2/4) INT8 packed
    localparam MAX_R_WORDS  = MAX_DIM * MAX_DIM;             // MAX_DIM×MAX_DIM INT32 results
    localparam TILE_SIZE    = 64;             // fixed hardware tile dimension

    //=========================================================================
    // DUT Signals
    //=========================================================================
    reg         clk;
    reg         rst_n;

    // MMIO slave
    reg         cs;
    reg         we;
    reg  [11:0] addr;
    reg  [31:0] wdata;
    wire [31:0] rdata;
    wire        ready;

    // SRAM
    wire [31:0] sram_rdata;
    wire [11:0] weight_sram_addr;
    wire        weight_sram_wr_en;
    wire        weight_sram_rd_en;
    wire [11:0] activation_sram_addr;
    wire        activation_sram_wr_en;
    wire        activation_sram_rd_en;
    wire [11:0] output_sram_addr;
    wire        output_sram_wr_en;
    wire [31:0] output_sram_wdata;

    // Interrupt
    wire        irq;

    // Broadcast buses (testbench-driven)
    reg  [255:0]  weight_bus;
    reg  [511:0]  activation_bus;

    // Output bus (testbench-captured)
    wire [2047:0] acc_out_bus_o;

    // Debug
    wire [3:0]  state;
    wire        compute_en_o;
    wire        weight_load_en_o;
    wire        activation_load_en_o;
    wire        store_out_o;
    wire [5:0]  store_row_o;
    wire [5:0]  compute_k_o;
    wire [15:0] tiles_completed_o;

    //=========================================================================
    // DUT Instantiation
    //=========================================================================
    mxu_top #(.ADDR_WIDTH(12)) u_dut (
        .clk                (clk),
        .rst_n              (rst_n),
        .cs                 (cs),
        .we                 (we),
        .addr               (addr),
        .wdata              (wdata),
        .rdata              (rdata),
        .ready              (ready),
        .sram_rdata         (sram_rdata),
        .weight_sram_addr   (weight_sram_addr),
        .weight_sram_wr_en  (weight_sram_wr_en),
        .weight_sram_rd_en  (weight_sram_rd_en),
        .activation_sram_addr  (activation_sram_addr),
        .activation_sram_wr_en (activation_sram_wr_en),
        .activation_sram_rd_en (activation_sram_rd_en),
        .output_sram_addr   (output_sram_addr),
        .output_sram_wr_en  (output_sram_wr_en),
        .output_sram_wdata  (output_sram_wdata),
        .irq                (irq),
        .weight_bus_i       (weight_bus),
        .activation_bus_i   (activation_bus),
        .acc_out_bus_o      (acc_out_bus_o),
        .state                (state),
        .compute_en_o         (compute_en_o),
        .weight_load_en_o     (weight_load_en_o),
        .activation_load_en_o (activation_load_en_o),
        .store_out_o          (store_out_o),
        .store_row_o          (store_row_o),
        .compute_k_o          (compute_k_o),
        .tiles_completed_o    (tiles_completed_o)
    );

    // Tie off unused SRAM inputs
    assign sram_rdata = 32'd0;

    //=========================================================================
    // Clock and Reset Generation
    //=========================================================================
    initial clk = 1'b0;
    always #CLK_HALF clk = ~clk;

    //=========================================================================
    // Cycle Counter (for performance reporting)
    //=========================================================================
    reg [31:0] cycle_cnt;
    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            cycle_cnt <= 32'd0;
        end else begin
            cycle_cnt <= cycle_cnt + 32'd1;
        end
    end

    //=========================================================================
    // Test Scenario Parameters (parsed from +testdir+/params.txt)
    //=========================================================================
    reg [1023:0]  test_dir;           // from +testdir+ plusarg
    reg [1023:0]  params_path;        // {test_dir}/params.txt
    reg [1023:0]  w_hex_path;         // {test_dir}/weights.hex
    reg [1023:0]  a_hex_path;         // {test_dir}/activations.hex
    reg [1023:0]  g_hex_path;         // {test_dir}/golden_output.hex
    reg [1023:0]  result_path;        // CaduceusCore/rtl/results/mxu_<scenario>.hex
    reg [1023:0]  scenario_name;      // last component of test_dir

    reg [15:0]    M, K, N;            // matrix dimensions
    reg [31:0]    weight_words;       // ceil(M*K/8)
    reg [31:0]    act_words;          // ceil(K*N/4)
    reg [31:0]    result_words;       // M * N
    reg [15:0]    k_tiles, n_tiles, m_tiles; // ceil(dim/TILE_SIZE)

    // Performance timing
    time          start_time;
    time          irq_time;

    //=========================================================================
    // Internal Memories (loaded via $readmemh)
    //=========================================================================
    reg [31:0] weight_mem [0:MAX_W_WORDS-1];
    reg [31:0] act_mem    [0:MAX_A_WORDS-1];
    reg [31:0] golden_mem [0:MAX_R_WORDS-1];
    reg [31:0] result_mem [0:MAX_R_WORDS-1];

    //=========================================================================
    // Compute Bus Driver State (negedge clock domain)
    //=========================================================================
    reg [15:0]  global_k_off;         // accumulated K-offset from completed tiles
    reg [6:0]   comp_cycle;           // 0..k_cur+1 within current compute phase (7-bit)

    wire [16:0] k_rem_w = {1'b0, K} - {1'b0, global_k_off};
    wire [6:0]  k_cur_w = (k_rem_w >= TILE_SIZE) ? TILE_SIZE : k_rem_w[6:0];

    //=========================================================================
    // Tile Tracker (tracks controller tile progression)
    //=========================================================================
    reg [15:0]  tb_k_tile, tb_n_tile, tb_m_tile;
    reg [15:0]  cap_m_tile, cap_n_tile; // latched tile indices for the current store phase
    reg         start_trackers;       // pulse: reset tile trackers to initial state

    // Falling-edge detector for compute_en → tile transitions
    reg         compute_en_prev;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            compute_en_prev <= 1'b0;
        end else begin
            compute_en_prev <= compute_en_o;
        end
    end

    wire compute_fell = compute_en_prev && !compute_en_o;

    //=========================================================================
    // Result Capture (posedge clk, captures store_out rows)
    //=========================================================================
    reg [31:0]  result_count;         // number of INT32 values captured
    reg [5:0]   prev_store_row;       // dedup: last captured store_row
    reg         cap_first;            // first capture in store phase
    integer     cap_c;
    integer     cap_flat;             // row-major flat index into result_mem

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            result_count    <= 32'd0;
            prev_store_row  <= 6'd0;
            cap_first       <= 1'b1;
        end else if (store_out_o) begin
            if (cap_first || (store_row_o != prev_store_row)) begin
                integer    dim_rem_n_cap;
                reg [6:0]  cap_tile_n_cur;

                cap_first       <= 1'b0;
                prev_store_row  <= store_row_o;

                // Compute valid columns for this capture tile from the latched
                // N-tile index. Doing it here avoids the one-cycle lag from
                // computing it in the negedge block.
                dim_rem_n_cap  = {1'b0, N} - {1'b0, (cap_n_tile * TILE_SIZE)};
                cap_tile_n_cur = (dim_rem_n_cap >= TILE_SIZE) ? TILE_SIZE : dim_rem_n_cap[6:0];

                // Capture valid columns for this N-tile into row-major slots.
                // Use latched cap_m_tile/cap_n_tile so the index remains stable
                // for the entire store_out phase even though tb_m/tb_n advance
                // at compute_en falling edge.
                // Absolute row = cap_m_tile*TILE_SIZE + store_row_o,
                // absolute col = cap_n_tile*TILE_SIZE + cap_c.
                for (cap_c = 0; cap_c < cap_tile_n_cur && cap_c < TILE_SIZE; cap_c = cap_c + 1) begin
                    cap_flat = (cap_m_tile * TILE_SIZE + {10'd0, store_row_o}) * N
                             + (cap_n_tile * TILE_SIZE + cap_c);
                    result_mem[cap_flat] <= acc_out_bus_o[32*cap_c +: 32];
                end
                result_count <= result_count + {26'd0, cap_tile_n_cur};
            end
        end else begin
            cap_first <= 1'b1;
        end
    end

    //=========================================================================
    // Compute Bus Driving (negedge clk, avoids NBA races with DUT)
    //=========================================================================
    always @(negedge clk or negedge rst_n) begin : blk_compute_drive
        integer drv_r, drv_c;
        reg [31:0] drv_w_word, drv_a_word;
        integer    drv_nibble_idx;  // integer: avoid 3-bit truncation on << 2
        integer    drv_byte_idx;    // integer: avoid 2-bit truncation on << 3
        integer    w_flat, a_flat;  // flat byte/nibble indices into packed hex arrays
        reg [15:0] drv_k_idx;

        if (!rst_n) begin
            weight_bus      <= 256'd0;
            activation_bus  <= 512'd0;
            comp_cycle      <= 7'd0;
            global_k_off    <= 16'd0;
            tb_k_tile       <= 16'd0;
            tb_n_tile       <= 16'd0;
            tb_m_tile       <= 16'd0;
        end else if (start_trackers) begin
            // Initial block requests tracker reset (before CMD=START)
            global_k_off    <= 16'd0;
            tb_k_tile       <= 16'd0;
            tb_n_tile       <= 16'd0;
            tb_m_tile       <= 16'd0;
            cap_m_tile      <= 16'd0;
            cap_n_tile      <= 16'd0;
            comp_cycle      <= 7'd0;
            weight_bus      <= 256'd0;
            activation_bus  <= 512'd0;
        end else if (compute_en_o) begin
            if (comp_cycle < k_cur_w) begin
                // Drive real data for K-index = global_k_off + comp_cycle
                drv_k_idx = global_k_off + {9'd0, comp_cycle};

                // ── Weight broadcast bus (column broadcast) ───────────
                // weights.hex stores K×N INT4 row-major (K rows, N cols), packed
                // 8 weights per 32-bit word. PE(r,c) at K-cycle k needs weight[k][c].
                // Absolute column = tb_n_tile*TILE_SIZE + c.
                // Flat index = k*N + abs_col; word_idx = flat_idx / 8;
                // nibble = flat_idx % 8.
                weight_bus = 256'd0;
                for (drv_c = 0; drv_c < TILE_SIZE; drv_c = drv_c + 1) begin
                    w_flat         = drv_k_idx * N + (tb_n_tile * TILE_SIZE + drv_c);
                    drv_nibble_idx = w_flat & 32'd7;
                    drv_w_word     = weight_mem[w_flat >> 3];
                    weight_bus[4*drv_c +: 4] = (drv_w_word >> (drv_nibble_idx * 4)) & 4'hF;
                end

                // ── Activation broadcast bus (row broadcast) ──────────
                // activations.hex stores M×K INT8 row-major (M rows, K cols), packed
                // 4 activations per 32-bit word. PE(r,c) at K-cycle k needs act[r][k].
                // Absolute row = tb_m_tile*TILE_SIZE + r.
                // Flat index = abs_row*K + k; word_idx = flat_idx / 4;
                // byte = flat_idx % 4.
                activation_bus = 512'd0;
                for (drv_r = 0; drv_r < TILE_SIZE; drv_r = drv_r + 1) begin
                    a_flat       = (tb_m_tile * TILE_SIZE + drv_r) * K + drv_k_idx;
                    drv_byte_idx = a_flat & 32'd3;
                    drv_a_word   = act_mem[a_flat >> 2];
                    activation_bus[8*drv_r +: 8] = (drv_a_word >> (drv_byte_idx * 8)) & 8'hFF;
                end

            end else begin
                // Flush cycles: drive zero
                weight_bus      <= 256'd0;
                activation_bus  <= 512'd0;
            end
            comp_cycle <= comp_cycle + 7'd1;
        end else begin
            comp_cycle <= 7'd0;
            weight_bus      <= 256'd0;
            activation_bus  <= 512'd0;

            // On compute_en falling edge, latch the tile indices for the
            // upcoming store_out phase, then advance the live trackers.
            if (compute_fell) begin
                cap_m_tile <= tb_m_tile;
                cap_n_tile <= tb_n_tile;

                // Advance K-tile; check for N/M tile wrap. Use strict `<`
                // so live tile indices stay within the current group during
                // the final store_out phase.
                tb_k_tile <= tb_k_tile + 16'd1;
                if ((tb_k_tile + 16'd1) < k_tiles) begin
                    // More K-tiles in this (M,N) group: accumulate K offset
                    global_k_off <= global_k_off + {9'd0, k_cur_w};
                end else begin
                    // Last K-tile of this group: reset K offset and move to
                    // the next N-tile (or M-tile) only if one exists.
                    tb_k_tile    <= 16'd0;
                    global_k_off <= 16'd0;
                    if ((tb_n_tile + 16'd1) < n_tiles) begin
                        tb_n_tile <= tb_n_tile + 16'd1;
                    end else begin
                        tb_n_tile <= 16'd0;
                        if ((tb_m_tile + 16'd1) < m_tiles) begin
                            tb_m_tile <= tb_m_tile + 16'd1;
                        end
                        // else: last M-tile; leave tb_m_tile at final value
                    end
                end
            end
        end
    end

    //=========================================================================
    // MMIO Helpers — drive cs/we/addr/wdata on negedge, stable before posedge
    //=========================================================================
    task mmio_write;
        input [11:0] reg_addr;
        input [31:0] value;
    begin
        @(negedge clk);
        cs   = 1'b1;
        we   = 1'b1;
        addr = reg_addr;
        wdata = value;
        @(negedge clk);
        cs   = 1'b0;
        we   = 1'b0;
        addr = 12'd0;
        wdata = 32'd0;
    end
    endtask

    task mmio_read;
        input  [11:0] reg_addr;
        output [31:0] value;
    begin
        @(negedge clk);
        cs   = 1'b1;
        we   = 1'b0;
        addr = reg_addr;
        @(negedge clk);
        value = rdata;
        cs   = 1'b0;
        addr = 12'd0;
    end
    endtask

    //=========================================================================
    // MAIN TEST SEQUENCE
    //=========================================================================
    reg [31:0] stat_val;
    reg [31:0] total_expected;
    reg [31:0] mismatch_count;
    reg [31:0] first_mismatch;
    integer    cmp_i;
    integer    fd, code, scans;
    reg [31:0]   val_int;

    initial begin
        // ── Initialize signals ────────────────────────────────────────────
        cs      = 1'b0;
        we      = 1'b0;
        addr    = 12'd0;
        wdata   = 32'd0;
        weight_bus     = 256'd0;
        activation_bus = 512'd0;

        // ── Reset sequence ────────────────────────────────────────────────
        rst_n = 1'b0;
        repeat(5) @(posedge clk);
        rst_n = 1'b1;
        @(posedge clk);
        $display("[TB] Reset released at %0t", $time);

        // ── Step 1: Read +testdir+ plusarg ────────────────────────────────
        if (!$value$plusargs("testdir=%s", test_dir)) begin
            $display("[TB] ERROR: +testdir+ plusarg not provided");
            $display("[TB] Usage: ./simv_mxu +testdir=<path_to_scenario_dir>");
            $finish;
        end
        $display("[TB] testdir = %0s", test_dir);

        // ── Step 2: Parse params.txt ──────────────────────────────────────
        // params.txt format: M=<value>\nK=<value>\nN=<value>\n
        // Use $fscanf with %c to read single key character (avoids %s issue)
        $sformat(params_path, "%0s/params.txt", test_dir);
        fd = $fopen(params_path, "r");
        if (!fd) begin
            $display("[TB] ERROR: Cannot open %0s", params_path);
            $finish;
        end

        M = 16'd0; K = 16'd0; N = 16'd0;
        begin
            reg [7:0] key_char;
            for (scans = 0; scans < 3; scans = scans + 1) begin
                code = $fscanf(fd, "%c=%d\n", key_char, val_int);
                if (code != 2) begin
                    $display("[TB] ERROR: params.txt parse failed at line %0d (code=%0d)", scans, code);
                    $fclose(fd);
                    $finish;
                end
                case (key_char)
                    "M": M = val_int[15:0];
                    "K": K = val_int[15:0];
                    "N": N = val_int[15:0];
                    default: $display("[TB] WARN: unknown key '%c' (0x%0h)", key_char, key_char);
                endcase
            end
        end
        $fclose(fd);

        $display("[TB] Parsed dimensions: M=%0d, K=%0d, N=%0d", M, K, N);

        // Validate: zero-dimension → controller skips to DONE; handle gracefully
        if (M == 0 || K == 0 || N == 0) begin
            $display("[TB] NOTE: Zero dimension detected (M=%0d, K=%0d, N=%0d)", M, K, N);
            $display("[TB] Controller should skip directly to DONE.");
        end

        // Compute derived sizes
        weight_words = ((M * K) + 7) / 8;   // ceil(M*K/8)
        act_words    = ((K * N) + 3) / 4;   // ceil(K*N/4)
        result_words = M * N;
        total_expected = result_words;

        k_tiles = (K + (TILE_SIZE - 1)) / TILE_SIZE;
        n_tiles = (N + (TILE_SIZE - 1)) / TILE_SIZE;
        m_tiles = (M + (TILE_SIZE - 1)) / TILE_SIZE;

        $display("[TB] weight_words=%0d, act_words=%0d, result_words=%0d, tiles: K=%0d N=%0d M=%0d",
                 weight_words, act_words, result_words, k_tiles, n_tiles, m_tiles);

        // ── Step 3: Load hex files via $readmemh ──────────────────────────
        $sformat(w_hex_path, "%0s/weights.hex", test_dir);
        $sformat(a_hex_path, "%0s/activations.hex", test_dir);
        $sformat(g_hex_path, "%0s/golden_output.hex", test_dir);

        $display("[TB] Loading weights from %0s", w_hex_path);
        $readmemh(w_hex_path, weight_mem);

        $display("[TB] Loading activations from %0s", a_hex_path);
        $readmemh(a_hex_path, act_mem);

        $display("[TB] Loading golden_output from %0s", g_hex_path);
        $readmemh(g_hex_path, golden_mem);

        // ── Step 4: Configure MMIO registers ──────────────────────────────
        // CTRL=0 (INT4×INT8 dtype)
        mmio_write(12'h00, 32'd0);
        $display("[TB] Wrote CTRL=0 (INT4xINT8 mode)");

        // DIM0 = {K[15:0], M[15:0]}
        mmio_write(12'h0C, {K[15:0], M[15:0]});
        $display("[TB] Wrote DIM0: K=%0d, M=%0d", K, M);

        // DIM1 = {16'd0, N[15:0]}
        mmio_write(12'h10, {16'd0, N[15:0]});
        $display("[TB] Wrote DIM1: N=%0d", N);

        // I_ADDR, W_ADDR, O_ADDR (any values for Phase 1)
        mmio_write(12'h14, 32'd0);
        mmio_write(12'h18, 32'd0);
        mmio_write(12'h1C, 32'd0);

        // IRQ_EN = 1
        mmio_write(12'h28, 32'd1);
        $display("[TB] Wrote IRQ_EN=1");

        // Reset tile trackers before starting (pulse start_trackers flag)
        // Set BEFORE negedge to ensure deterministic detection by always block
        start_trackers = 1'b1;
        @(negedge clk);
        start_trackers = 1'b0;
        @(negedge clk);  // let always block process and clear

        // CMD = 1 (START)
        mmio_write(12'h04, 32'd1);
        start_time = $time * 1000;
        $display("[TB] Wrote CMD=START at %0t", $time);

        // ── Step 5: Wait for STATUS.DONE or IRQ ──────────────────────────
        $display("[TB] Waiting for STATUS.DONE or IRQ...");
        fork : wait_done
            begin
                // Poll STATUS register
                repeat(1000000) begin
                    mmio_read(12'h08, stat_val);
                    if (stat_val[1]) begin  // DONE bit
                        $display("[TB] STATUS.DONE asserted at %0t", $time);
                        disable wait_done;
                    end
                    @(posedge clk);
                end
                $display("[TB] ERROR: Timeout waiting for STATUS.DONE");
                $finish;
            end
            begin
                // Wait for IRQ
                @(posedge irq);
                irq_time = $time * 1000;
                $display("[TB] IRQ asserted at %0t", $time);
                $display("[TB] *** PERF: total_cycles=%0d, M=%0d, K=%0d, N=%0d, tiles_K=%0d, tiles_N=%0d, tiles_M=%0d",
                         cycle_cnt, M, K, N, k_tiles, n_tiles, m_tiles);
                disable wait_done;
            end
        join

        // Wait a few extra cycles for any trailing store_out
        repeat(5) @(posedge clk);

        $display("[TB] Operation complete. Captured %0d INT32 values (expected %0d)",
                 result_count, total_expected);

        // ── Step 6: Write captured result to hex file ─────────────────────
        // Extract scenario name: prefer +scenario+ plusarg, fallback to
        // last component of test_dir (byte scanning on packed regs unreliable).
        if (!$value$plusargs("scenario=%s", scenario_name)) begin
            // Fallback: copy entire test_dir into unpacked array first,
            // then scan for '/'
            begin
                integer si, ls, sj;
                reg [7:0] db [0:127];
                for (si = 0; si < 128; si = si + 1) begin
                    db[si] = test_dir[si*8 +: 8];
                end
                ls = 0;
                for (si = 0; si < 128; si = si + 1) begin
                    if (db[si] == 8'h2F) ls = si + 1;  // '/'
                    if (db[si] == 8'h00) break;
                end
                sj = 0;
                for (si = ls; si < 128; si = si + 1) begin
                    if (db[si] == 8'h00) break;
                    scenario_name[sj*8 +: 8] = db[si];
                    sj = sj + 1;
                end
                // If still empty, use default
                if (sj == 0) begin
                    scenario_name = 1024'd0;
                    scenario_name[7:0]   = "u";
                    scenario_name[15:8]  = "n";
                    scenario_name[23:16] = "k";
                end
            end
        end

        $sformat(result_path, "CaduceusCore/rtl/results/mxu_%0s.hex", scenario_name);
        $display("[TB] Writing result to %0s", result_path);

        if (result_count == 0) begin
            // Zero-dimension case: $writememh with end=-1 is illegal; create
            // an empty result file explicitly.
            fd = $fopen(result_path, "w");
            $fclose(fd);
        end else begin
            $writememh(result_path, result_mem, 0, result_count - 1);
        end

        // ── Step 7: Compare with golden_output.hex ────────────────────────
        mismatch_count = 32'd0;
        first_mismatch = 32'hFFFFFFFF;

        if (total_expected == 0) begin
            $display("[TB] Zero-dimension test: no output expected.");
            if (result_count == 0) begin
                $display("[TB] PASS: No result captured (as expected).");
                $display("PASS");
            end else begin
                $display("[TB] FAIL: Expected 0 results but captured %0d.", result_count);
                $display("FAIL");
            end
        end else begin
            for (cmp_i = 0; cmp_i < total_expected && cmp_i < result_count; cmp_i = cmp_i + 1) begin
                if (result_mem[cmp_i] !== golden_mem[cmp_i]) begin
                    if (mismatch_count == 0) first_mismatch = cmp_i[31:0];
                    mismatch_count = mismatch_count + 32'd1;
                    if (mismatch_count <= 5) begin
                        $display("  MISMATCH [%0d]: golden=0x%08h, result=0x%08h",
                                 cmp_i, golden_mem[cmp_i], result_mem[cmp_i]);
                    end
                end
            end

            if (result_count != total_expected) begin
                $display("[TB] WARNING: Captured %0d results but expected %0d",
                         result_count, total_expected);
            end

            if (mismatch_count == 0 && result_count >= total_expected) begin
                $display("[TB] PASS: All %0d INT32 values match golden_output.hex", total_expected);
                $display("PASS");
            end else if (mismatch_count > 0) begin
                $display("[TB] FAIL: %0d mismatches (first at index %0d)",
                         mismatch_count, first_mismatch);
                $display("FAIL");
            end else begin
                $display("[TB] FAIL: Only captured %0d / %0d expected values",
                         result_count, total_expected);
                $display("FAIL");
            end
        end

        $display("[TB] *** PERF: elapsed_start_to_irq_cycles=%0d", (irq_time - start_time) / 1000);
        $finish;
    end

endmodule
