//=============================================================================
// gelu_hw — 4-stage streaming GELU pipeline
//=============================================================================
// Input/output: IEEE-754 FP16. One element per cycle, no back-pressure.
//
// Algorithm (matches GoldenSFU.gelu_hw):
//   x < -4        -> 0
//   x >  4        -> x
//   -4 <= x <= 4  -> linear interpolation of 64-entry GELU LUT
//
// LUT:
//   64 entries over [-4, 4], signed Q3.12 fixed-point.
//   Generated by CaduceusCore/sim/scripts/gen_sfu_luts.py from the tanh
//   approximation gelu(x) = 0.5*x*(1+tanh(sqrt(2/pi)*(x+0.044715*x^3))).
//
// Pipeline stages:
//   S1: FP16 -> signed fixed-point; compute delta; set below/above flags.
//   S2: Compute LUT index and Q0.12 fraction; read LUT lo/hi entries.
//   S3: Linear interpolation in fixed-point.
//   S4: Select 0 / pass-through x / interpolated value; convert to FP16.
//=============================================================================

`timescale 1ns / 1ps

module gelu_hw (
    input  wire        clk,
    input  wire        rst_n,
    input  wire [15:0] data_i,
    input  wire        valid_i,
    output reg  [15:0] data_o,
    output reg         valid_o
);

    localparam ENTRIES    = 64;
    localparam FRAC       = 12;
    localparam FXW        = 32;
    localparam LUT_W      = 16;
    localparam IDX_BITS   = 6;

    // [-4, 4] mapped to fixed-point. RANGE_FX = 8 * 2^FRAC = 2^(FRAC+3).
    localparam integer XMIN_FX  = -4 * (1 << FRAC);
    localparam integer XMAX_FX  =  4 * (1 << FRAC);
    localparam integer RANGE_FX =  8 * (1 << FRAC);

    // LUT ROM (signed Q3.12). Path can be overridden at compile time.
`ifndef GELU_LUT_PATH
    `define GELU_LUT_PATH "CaduceusCore/rtl/test_vectors/sfu/luts/gelu_lut.hex"
`endif
    reg signed [LUT_W-1:0] gelu_lut [0:ENTRIES-1];
    initial begin
        $readmemh(`GELU_LUT_PATH, gelu_lut);
    end

    // Stage 1 -> 2
    reg [15:0]        s1_x_fp16;
    reg               s1_valid;
    reg signed [FXW-1:0] s1_delta;
    reg               s1_below;
    reg               s1_above;

    // Stage 2 -> 3
    reg [15:0]        s2_x_fp16;
    reg               s2_valid;
    reg               s2_below;
    reg               s2_above;
    reg signed [LUT_W-1:0] s2_lut_lo;
    reg signed [LUT_W-1:0] s2_lut_hi;
    reg signed [FRAC-1:0]  s2_frac;

    // Stage 3 -> 4
    reg [15:0]        s3_x_fp16;
    reg               s3_valid;
    reg               s3_below;
    reg               s3_above;
    reg signed [LUT_W+1:0] s3_interp;

    //-------------------------------------------------------------------------
    // Fixed-point helpers
    //-------------------------------------------------------------------------

    function automatic signed [FXW-1:0] fp16_to_fixed;
        input [15:0] a;
        reg sign;
        reg [4:0]  exp;
        reg [9:0]  mant;
        reg [10:0] sig;
        integer    shift;
        begin
            if ((a & 16'h7FFF) == 16'h0000) begin
                fp16_to_fixed = 0;
            end else begin
                sign = a[15];
                exp  = a[14:10];
                mant = a[9:0];
                if (exp == 5'd0) begin
                    fp16_to_fixed = 0;
                end else begin
                    sig = {1'b1, mant};
                    shift = $signed({1'b0, exp}) - 25 + FRAC;
                    if (shift >= 0) begin
                        fp16_to_fixed = sign
                            ? -$signed({{(FXW-11){1'b0}}, sig} << shift)
                            :  $signed({{(FXW-11){1'b0}}, sig} << shift);
                    end else begin
                        fp16_to_fixed = sign
                            ? -$signed(($signed({{(FXW-11){1'b0}}, sig})
                                        + (1 << (-shift - 1))) >> (-shift))
                            :  $signed(($signed({{(FXW-11){1'b0}}, sig})
                                        + (1 << (-shift - 1))) >> (-shift));
                    end
                end
            end
        end
    endfunction

    function automatic [15:0] fixed_to_fp16;
        input signed [LUT_W+1:0] f;
        reg sign;
        reg [LUT_W+1:0] abs_f;
        integer msb;
        integer e;
        integer exp;
        integer shift;
        reg [11:0] m_rounded;
        reg [LUT_W+1:0] round_mask;
        reg [LUT_W+1:0] round_bits;
        reg [LUT_W+1:0] half;
        begin
            if (f == 0) begin
                fixed_to_fp16 = 16'h0000;
            end else begin
                sign  = (f < 0);
                abs_f = sign ? -$signed(f) : f;

                msb = LUT_W + 1;
                while (msb >= 0 && !abs_f[msb])
                    msb = msb - 1;

                e = msb - FRAC;

                if (e >= 16) begin
                    fixed_to_fp16 = {sign, 5'h1F, 10'h000};
                end else begin
                    shift = msb - 10;
                    if (shift > 0) begin
                        m_rounded  = abs_f >> shift;
                        round_mask = (1 << shift) - 1;
                        round_bits = abs_f & round_mask;
                        half       = 1 << (shift - 1);
                        if ((round_bits > half) ||
                            ((round_bits == half) && m_rounded[0])) begin
                            m_rounded = m_rounded + 1;
                        end
                    end else begin
                        m_rounded = abs_f << (-shift);
                    end

                    if (m_rounded[11]) begin
                        m_rounded = 12'd1024;
                        e = e + 1;
                    end

                    exp = e + 15;
                    fixed_to_fp16 = {sign, exp[4:0], m_rounded[9:0]};
                end
            end
        end
    endfunction

    //-------------------------------------------------------------------------
    // Pipeline
    //-------------------------------------------------------------------------

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            s1_x_fp16  <= 16'd0;
            s1_valid   <= 1'b0;
            s1_delta   <= {FXW{1'b0}};
            s1_below   <= 1'b0;
            s1_above   <= 1'b0;

            s2_x_fp16  <= 16'd0;
            s2_valid   <= 1'b0;
            s2_below   <= 1'b0;
            s2_above   <= 1'b0;
            s2_lut_lo  <= {LUT_W{1'b0}};
            s2_lut_hi  <= {LUT_W{1'b0}};
            s2_frac    <= {FRAC{1'b0}};

            s3_x_fp16  <= 16'd0;
            s3_valid   <= 1'b0;
            s3_below   <= 1'b0;
            s3_above   <= 1'b0;
            s3_interp  <= {(LUT_W+2){1'b0}};

            data_o     <= 16'd0;
            valid_o    <= 1'b0;
        end else begin
            // S1: convert and classify
            s1_x_fp16 <= data_i;
            s1_valid  <= valid_i;
            begin
                reg signed [FXW-1:0] x_fx;
                x_fx = fp16_to_fixed(data_i);
                s1_delta <= x_fx - XMIN_FX;
                s1_below <= (x_fx < XMIN_FX);
                s1_above <= (x_fx > XMAX_FX);
            end

            // S2: index, fraction, LUT read
            s2_x_fp16 <= s1_x_fp16;
            s2_valid  <= s1_valid;
            s2_below  <= s1_below;
            s2_above  <= s1_above;
            begin
                reg [IDX_BITS-1:0] idx_lo;
                reg [IDX_BITS-1:0] idx_hi;
                reg [31:0] scaled;
                reg [31:0] idx_full;
                reg [31:0] frac_rem;
                reg signed [FRAC-1:0] frac;

                if (!s1_below && !s1_above) begin
                    scaled   = s1_delta * (ENTRIES - 1);
                    idx_full = scaled >> (FRAC + 3);
                    if (idx_full >= ENTRIES - 1) begin
                        idx_lo = ENTRIES - 1;
                        idx_hi = ENTRIES - 1;
                        frac   = {FRAC{1'b0}};
                    end else begin
                        idx_lo = idx_full[IDX_BITS-1:0];
                        idx_hi = idx_lo + 1'b1;
                        frac_rem = scaled - (idx_full << (FRAC + 3));
                        frac     = frac_rem[FRAC+2:3];
                    end
                end else begin
                    idx_lo = {IDX_BITS{1'b0}};
                    idx_hi = {IDX_BITS{1'b0}};
                    frac   = {FRAC{1'b0}};
                end

                s2_lut_lo <= gelu_lut[idx_lo];
                s2_lut_hi <= gelu_lut[idx_hi];
                s2_frac   <= frac;
            end

            // S3: linear interpolation
            s3_x_fp16 <= s2_x_fp16;
            s3_valid  <= s2_valid;
            s3_below  <= s2_below;
            s3_above  <= s2_above;
            begin
                reg signed [LUT_W:0]   lut_diff;
                reg signed [LUT_W+FRAC:0] interp_prod;
                reg signed [LUT_W+1:0] interp_val;

                lut_diff   = s2_lut_hi - s2_lut_lo;
                interp_prod = lut_diff * $signed({1'b0, s2_frac});
                interp_val = s2_lut_lo + (interp_prod >>> FRAC);
                s3_interp  <= interp_val;
            end

            // S4: select and convert to FP16
            if (s3_below)
                data_o <= 16'h0000;
            else if (s3_above)
                data_o <= s3_x_fp16;
            else
                data_o <= fixed_to_fp16(s3_interp);
            valid_o <= s3_valid;
        end
    end

endmodule
