#!/usr/bin/env python3
"""
NPU ABI Schema Generator

Reads spec/npu_abi.json and generates deterministic bindings for:
  - Python:   gen/npu_abi.py
  - C:        gen/npu_abi.h
  - Firmware: gen/npu_abi_firmware.h
  - SystemVerilog: gen/npu_abi_pkg.sv
  - Markdown: gen/npu_abi.md

Modes:
  python3 scripts/gen_npu_abi.py --generate       # write artifacts
  python3 scripts/gen_npu_abi.py --check           # validate artifacts match schema (exit 0/1)

Two consecutive --generate runs produce byte-identical output.
"""

import argparse
import filecmp
import json
import os
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any


# ── Constants ───────────────────────────────────────────────────────
GENERATED_MARKER = (
    "DO NOT EDIT — generated by scripts/gen_npu_abi.py from spec/npu_abi.json"
)

REPO = Path(__file__).resolve().parent.parent
SCHEMA_PATH = REPO / "spec" / "npu_abi.json"


# ═════════════════════════════════════════════════════════════════════
# Schema loader
# ═════════════════════════════════════════════════════════════════════

def load_schema() -> dict[str, Any]:
    """Load and validate the ABI schema JSON."""
    if not SCHEMA_PATH.is_file():
        sys.exit(f"ERROR: Schema not found at {SCHEMA_PATH}")
    with open(SCHEMA_PATH, encoding="utf-8") as f:
        data = json.load(f)
    _validate_schema(data)
    return data


def _validate_schema(data: dict[str, Any]) -> None:
    """Basic structural validation of the schema."""
    required_top = ["abi", "address_regions", "modules", "opcodes",
                    "descriptors", "rings", "capability_bits"]
    for key in required_top:
        if key not in data:
            sys.exit(f"Schema validation error: missing top-level key '{key}'")

    # Validate registers don't overlap within a module
    for mod_name, mod in data["modules"].items():
        seen: dict[int, str] = {}
        for reg_name, reg in sorted(mod.get("registers", {}).items(),
                                     key=lambda x: int(x[1]["offset"], 16)):
            off = int(reg["offset"], 16)
            if off in seen:
                sys.exit(
                    f"Schema error: {mod_name}.{reg_name} offset 0x{off:02X} "
                    f"collides with {mod_name}.{seen[off]}"
                )
            seen[off] = reg_name


# ═════════════════════════════════════════════════════════════════════
# Python generator
# ═════════════════════════════════════════════════════════════════════

def gen_python(schema: dict[str, Any]) -> str:
    """Generate Python constants module."""
    lines: list[str] = []
    lines.append(f"# {GENERATED_MARKER}")
    lines.append(f"# ABI version: {schema['abi']['version_string']}")
    lines.append("")
    lines.append('"""')
    lines.append(f"  CaduceusCore NPU ABI v{schema['abi']['version_string']}")
    lines.append(f"  Generated from: spec/npu_abi.json")
    lines.append('"""')
    lines.append("")
    lines.append("from enum import IntEnum")
    lines.append("")

    # Address regions
    lines.append("# ═══ Address Regions ═══")
    lines.append("")
    lines.append("class Addr:")
    lines.append('    """Base addresses (byte-addressable, 32-bit aligned)."""')
    for name in sorted(schema["address_regions"]):
        reg = schema["address_regions"][name]
        base = int(reg["base"], 16)
        lines.append(f"    {name:22s} = 0x{base:08X}")
    lines.append("")
    lines.append("")

    # Modules
    for mod_name in sorted(schema["modules"]):
        mod = schema["modules"][mod_name]
        lines.append(f"# ═══ {mod_name} ({mod['base']}) ═══")
        lines.append(f"# {mod.get('description', '')}")
        lines.append("")
        lines.append(f"class {mod_name}:")
        lines.append(f"    BASE = Addr.{mod_name}")
        lines.append("")
        for reg_name in sorted(mod["registers"]):
            reg = mod["registers"][reg_name]
            off = int(reg["offset"], 16)
            desc = reg.get("description", "")
            access = reg.get("access", "").upper()
            fields_str = ""
            if "fields" in reg:
                fields_strs = []
                for fname, finfo in sorted(reg["fields"].items()):
                    bits = finfo["bits"]
                    if bits[0] == bits[1]:
                        fields_strs.append(f"bit[{bits[0]}]={fname}")
                    else:
                        fields_strs.append(f"[{bits[0]}:{bits[1]}]={fname}")
                fields_str = " (" + ", ".join(fields_strs) + ")"
            arr = ""
            if reg.get("array_size"):
                arr = f" [{reg['array_size']}]"
            lines.append(f"    {reg_name:22s} = 0x{off:04X}  # {access}: {desc}{fields_str}{arr}")
        lines.append("")
        lines.append("")

    # Opcodes (engine-level)
    lines.append("# ═══ Engine Opcodes (firmware dispatch) ═══")
    lines.append("")
    lines.append("class EngineOp(IntEnum):")
    lines.append('    """Engine-level opcode shared between host (Python) and firmware (C)."""')
    opcode_values = schema["opcodes"]["values"]
    for name in sorted(opcode_values, key=lambda n: opcode_values[n]["value"]):
        oc = opcode_values[name]
        lines.append(f"    {name:22s} = {oc['value']:#04x}  # {oc['engine']}: {oc['description']}")
    lines.append("")
    lines.append("")

    # ISA opcodes
    lines.append("# ═══ ISA Opcodes (instruction set) ═══")
    lines.append("")
    lines.append("class OpCode(IntEnum):")
    lines.append('    """NPU instruction opcodes (5-bit)."""')
    isa_values = schema["isa_opcodes"]["values"]
    for name in sorted(isa_values, key=lambda n: isa_values[n]["value"]):
        oc = isa_values[name]
        lines.append(f"    {name:22s} = {oc['value']:#04x}  # {oc['description']}")
    lines.append("")
    lines.append("")

    # Status codes
    lines.append("# ═══ Status Codes ═══")
    lines.append("")
    lines.append("class StatusCode(IntEnum):")
    for name in sorted(schema["status_codes"]["values"],
                        key=lambda n: schema["status_codes"]["values"][n]["value"]):
        sc = schema["status_codes"]["values"][name]
        lines.append(f"    {name:22s} = {sc['value']}  # {sc['description']}")
    lines.append("")
    lines.append("")

    # Capability bits
    lines.append("# ═══ Capability Bits ═══")
    lines.append("")
    for name in sorted(schema["capability_bits"]["bits"],
                        key=lambda n: schema["capability_bits"]["bits"][n]["bit"]):
        cb = schema["capability_bits"]["bits"][name]
        lines.append(f"CAP_{name} = 1 << {cb['bit']:2d}  # {cb['description']}")
    lines.append("")
    lines.append("")

    # SFU sub-opcodes
    lines.append("# ═══ SFU Sub-Opcodes ═══")
    lines.append("")
    lines.append("class SFUOp(IntEnum):")
    for name in sorted(schema["sfu_sub_opcodes"]["values"],
                        key=lambda n: schema["sfu_sub_opcodes"]["values"][n]["value"]):
        so = schema["sfu_sub_opcodes"]["values"][name]
        lines.append(f"    {name:22s} = {so['value']}  # {so['description']}")
    lines.append("")
    lines.append("")

    # Vector sub-opcodes
    lines.append("# ═══ Vector Sub-Opcodes ═══")
    lines.append("")
    lines.append("class VectorOp(IntEnum):")
    for name in sorted(schema["vector_sub_opcodes"]["values"],
                        key=lambda n: schema["vector_sub_opcodes"]["values"][n]["value"]):
        vo = schema["vector_sub_opcodes"]["values"][name]
        lines.append(f"    {name:22s} = {vo['value']}  # {vo['description']}")
    lines.append("")
    lines.append("")

    # MXU dtype
    lines.append("# ═══ MXU Data Types ═══")
    lines.append("")
    lines.append("class MXUDType(IntEnum):")
    for name in sorted(schema["mxu_dtype"]["values"],
                        key=lambda n: schema["mxu_dtype"]["values"][n]["value"]):
        dt = schema["mxu_dtype"]["values"][name]
        lines.append(f"    {name:22s} = {dt['value']}  # {dt['description']}")
    lines.append("")
    lines.append("")

    # INTC mappings
    lines.append("# ═══ Interrupt Source Bits ═══")
    lines.append("")
    for name in sorted(schema["intc_mappings"]["sources"],
                        key=lambda n: schema["intc_mappings"]["sources"][n]["bit"]):
        src = schema["intc_mappings"]["sources"][name]
        lines.append(f"INTC_{name:8s} = 1 << {src['bit']}  # {src['description']}")
    lines.append("")

    # Descriptor sizes
    lines.append("# ═══ Descriptor Sizes ═══")
    lines.append("")
    for desc_name in sorted(schema["descriptors"]):
        if desc_name == "description":
            continue
        desc = schema["descriptors"][desc_name]
        lines.append(f"DESC_{desc_name}_SIZE = {desc['packed_size']}  # {desc.get('notes', [''])[0] if desc.get('notes') else ''}")
    lines.append("")

    # Ring configuration
    lines.append("# ═══ Ring Buffer Configuration ═══")
    lines.append("")
    rc = schema["rings"]["configuration"]
    lines.append(f"RING_ENTRIES          = {rc['ring_entries']}")
    lines.append(f"CMD_ENTRY_SIZE        = {rc['cmd_entry_size']}")
    lines.append(f"COMPLETION_ENTRY_SIZE = {rc['completion_entry_size']}")
    lines.append("")

    return "\n".join(lines)


# ═════════════════════════════════════════════════════════════════════
# C header generator
# ═════════════════════════════════════════════════════════════════════

def gen_c_header(schema: dict[str, Any]) -> str:
    """Generate C/C++ header with defines and static_assert support."""
    lines: list[str] = []
    lines.append(f"/* {GENERATED_MARKER} */")
    lines.append(f"/* ABI version: {schema['abi']['version_string']} */")
    lines.append("")
    lines.append(f"#ifndef NPU_ABI_H")
    lines.append(f"#define NPU_ABI_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#ifdef __cplusplus")
    lines.append('extern "C" {')
    lines.append("#endif")
    lines.append("")

    # ABI version macros
    lines.append("/* ── ABI Version ─────────────────────────────────────────────── */")
    lines.append(f"#define NPU_ABI_MAJOR {schema['abi']['major']}")
    lines.append(f"#define NPU_ABI_MINOR {schema['abi']['minor']}")
    lines.append(f'#define NPU_ABI_VERSION_STRING "{schema["abi"]["version_string"]}"')
    lines.append("")

    # Address regions
    lines.append("/* ── Address Regions ────────────────────────────────────────── */")
    for name in sorted(schema["address_regions"]):
        reg = schema["address_regions"][name]
        base = int(reg["base"], 16)
        size = int(reg["size"], 16)
        lines.append(f"#define NPU_{name}_BASE 0x{base:08X}UL")
        lines.append(f"#define NPU_{name}_SIZE 0x{size:08X}UL")
    lines.append("")

    # Register offsets for each module
    for mod_name in sorted(schema["modules"]):
        mod = schema["modules"][mod_name]
        lines.append(f"/* ── {mod_name} Registers (base: NPU_{mod_name}_BASE) ──── */")
        for reg_name in sorted(mod["registers"]):
            reg = mod["registers"][reg_name]
            off = int(reg["offset"], 16)
            desc = reg.get("description", "").split("\n")[0]
            lines.append(f"#define NPU_{mod_name}_{reg_name}_OFFSET 0x{off:04X}UL  /* {desc} */")
        lines.append("")

    # Struct typedefs for each module
    for mod_name in sorted(schema["modules"]):
        mod = schema["modules"][mod_name]
        c_basename = mod_name.lower()
        lines.append(f"typedef struct {{")
        current_offset = 0
        for reg_name in sorted(mod["registers"], key=lambda n: int(mod["registers"][n]["offset"], 16)):
            reg = mod["registers"][reg_name]
            off = int(reg["offset"], 16)
            # Add padding if needed
            if off > current_offset:
                pad_bytes = off - current_offset
                lines.append(f"    uint8_t _pad_{current_offset:04x}[{pad_bytes}];")
            arr = ""
            if reg.get("array_size"):
                arr = f"[{reg['array_size']}]"
            lines.append(f"    volatile uint32_t {reg_name}{arr};  /* 0x{off:04X}: {reg.get('description', '')} */")
            current_offset = off + 4 * (reg.get("array_size", 1))
        lines.append(f"}} npu_{c_basename}_t;")
        lines.append("")

    # Engine opcodes
    lines.append("/* ── Engine Opcodes ─────────────────────────────────────────── */")
    opcode_values = schema["opcodes"]["values"]
    for name in sorted(opcode_values, key=lambda n: opcode_values[n]["value"]):
        oc = opcode_values[name]
        lines.append(f"#define NPU_ENGINE_OP_{name} {oc['value']}  /* {oc['engine']}: {oc['description']} */")
    lines.append("")

    # ISA opcodes
    lines.append("/* ── ISA Opcodes ────────────────────────────────────────────── */")
    isa_values = schema["isa_opcodes"]["values"]
    for name in sorted(isa_values, key=lambda n: isa_values[n]["value"]):
        oc = isa_values[name]
        lines.append(f"#define NPU_ISA_OP_{name} {oc['value']}  /* {oc['description']} */")
    lines.append("")

    # Status codes
    lines.append("/* ── Status Codes ───────────────────────────────────────────── */")
    for name in sorted(schema["status_codes"]["values"],
                        key=lambda n: schema["status_codes"]["values"][n]["value"]):
        sc = schema["status_codes"]["values"][name]
        lines.append(f"#define NPU_STATUS_{name} {sc['value']}  /* {sc['description']} */")
    lines.append("")

    # Capability bits
    lines.append("/* ── Capability Bits ────────────────────────────────────────── */")
    for name in sorted(schema["capability_bits"]["bits"],
                        key=lambda n: schema["capability_bits"]["bits"][n]["bit"]):
        cb = schema["capability_bits"]["bits"][name]
        lines.append(f"#define NPU_CAP_{name} (1U << {cb['bit']})  /* {cb['description']} */")
    lines.append("")

    # SFU opcodes
    lines.append("/* ── SFU Sub-Opcodes ────────────────────────────────────────── */")
    for name in sorted(schema["sfu_sub_opcodes"]["values"],
                        key=lambda n: schema["sfu_sub_opcodes"]["values"][n]["value"]):
        so = schema["sfu_sub_opcodes"]["values"][name]
        lines.append(f"#define SFU_OP_{name} {so['value']}  /* {so['description']} */")
    lines.append("")

    # Vector opcodes
    lines.append("/* ── Vector Sub-Opcodes ─────────────────────────────────────── */")
    for name in sorted(schema["vector_sub_opcodes"]["values"],
                        key=lambda n: schema["vector_sub_opcodes"]["values"][n]["value"]):
        vo = schema["vector_sub_opcodes"]["values"][name]
        lines.append(f"#define VEC_OP_{name} {vo['value']}  /* {vo['description']} */")
    lines.append("")

    # INTC bit mappings
    lines.append("/* ── Interrupt Source Bits ──────────────────────────────────── */")
    for name in sorted(schema["intc_mappings"]["sources"],
                        key=lambda n: schema["intc_mappings"]["sources"][n]["bit"]):
        src = schema["intc_mappings"]["sources"][name]
        lines.append(f"#define INTC_{name} (1U << {src['bit']})  /* {src['description']} */")
    lines.append("")

    # Ring configuration
    lines.append("/* ── Ring Buffer Configuration ──────────────────────────────── */")
    rc = schema["rings"]["configuration"]
    lines.append(f"#define NPU_RING_ENTRIES {rc['ring_entries']}")
    lines.append(f"#define NPU_CMD_ENTRY_SIZE {rc['cmd_entry_size']}")
    lines.append(f"#define NPU_COMPLETION_ENTRY_SIZE {rc['completion_entry_size']}")
    lines.append("")

    lines.append("#ifdef __cplusplus")
    lines.append("}")
    lines.append("#endif")
    lines.append("")
    lines.append("#endif /* NPU_ABI_H */")
    lines.append("")

    return "\n".join(lines)


# ═════════════════════════════════════════════════════════════════════
# Firmware header generator
# ═════════════════════════════════════════════════════════════════════

def gen_firmware_header(schema: dict[str, Any]) -> str:
    """Generate bare-metal firmware header (compatible with npu-regmap.h pattern)."""
    lines: list[str] = []
    lines.append(f"/* {GENERATED_MARKER} */")
    lines.append(f"/* ABI version: {schema['abi']['version_string']} */")
    lines.append(f"/* Include this alongside npu-regmap.h; it provides verifiable constants */")
    lines.append(f"/* for static_assert validation of ABI compliance. */")
    lines.append("")
    lines.append(f"#ifndef NPU_ABI_FIRMWARE_H")
    lines.append(f"#define NPU_ABI_FIRMWARE_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")

    # ABI version
    lines.append(f"#define NPU_ABI_MAJOR {schema['abi']['major']}")
    lines.append(f"#define NPU_ABI_MINOR {schema['abi']['minor']}")
    lines.append("")

    # Base address checks
    lines.append("/* ── ABI Base Address Constants (for static_assert) ──────────── */")
    for name in sorted(schema["address_regions"]):
        reg = schema["address_regions"][name]
        base = int(reg["base"], 16)
        size = int(reg["size"], 16)
        lines.append(f"#define NPU_ABI_{name}_BASE 0x{base:08X}UL")
        lines.append(f"#define NPU_ABI_{name}_SIZE 0x{size:08X}UL")
    lines.append("")

    # Descriptor sizes for static_assert
    lines.append("/* ── ABI Descriptor Sizes (for static_assert) ────────────────── */")
    for desc_name in sorted(schema["descriptors"]):
        if desc_name == "description":
            continue
        desc = schema["descriptors"][desc_name]
        lines.append(f"#define NPU_ABI_DESC_{desc_name}_PACKED_SIZE {desc['packed_size']}")
        lines.append(f"#define NPU_ABI_DESC_{desc_name}_FIELD_COUNT {desc['field_count']}")
    lines.append("")

    # Each descriptor field offset for static_assert
    for desc_name in sorted(schema["descriptors"]):
        if desc_name == "description":
            continue
        desc = schema["descriptors"][desc_name]
        lines.append(f"/* ── ABI {desc_name} Descriptor Field Offsets ────────────────── */")
        for field in desc["fields"]:
            lines.append(f"#define NPU_ABI_DESC_{desc_name}_{field['name']}_OFFSET {field['offset']}")
        lines.append("")

    # Ring sizes
    lines.append("/* ── ABI Ring Buffer Configuration ──────────────────────────── */")
    rc = schema["rings"]["configuration"]
    lines.append(f"#define NPU_ABI_RING_ENTRIES {rc['ring_entries']}")
    lines.append(f"#define NPU_ABI_CMD_ENTRY_SIZE {rc['cmd_entry_size']}")
    lines.append(f"#define NPU_ABI_COMPLETION_ENTRY_SIZE {rc['completion_entry_size']}")
    lines.append("")

    # Engine opcodes
    lines.append("/* ── ABI Engine Opcodes ─────────────────────────────────────── */")
    opcode_values = schema["opcodes"]["values"]
    for name in sorted(opcode_values, key=lambda n: opcode_values[n]["value"]):
        oc = opcode_values[name]
        lines.append(f"#define NPU_ABI_ENGINE_OP_{name} {oc['value']}  /* {oc['engine']} */")
    lines.append("")

    # Status codes
    lines.append("/* ── ABI Status Codes ───────────────────────────────────────── */")
    for name in sorted(schema["status_codes"]["values"],
                        key=lambda n: schema["status_codes"]["values"][n]["value"]):
        sc = schema["status_codes"]["values"][name]
        lines.append(f"#define NPU_ABI_STATUS_{name} {sc['value']}")
    lines.append("")

    # DOORBELL known discrepancy note
    lines.append("/* ── Known Discrepancy: DOORBELL COMPLETION_STATUS ──────────── */")
    lines.append("/* COMPLETION_STATUS hardware window is 16 entries (offset 0x14). */")
    lines.append("/* Firmware writes COMPLETION_STATUS[cmd_id] with cmd_id up to */")
    lines.append(f"/* NPU_ABI_RING_ENTRIES-1 ({rc['ring_entries'] - 1}). This is a */")
    lines.append("/* known design gap that must be resolved in a future ABI revision. */")
    lines.append("")

    lines.append("#endif /* NPU_ABI_FIRMWARE_H */")
    lines.append("")

    return "\n".join(lines)


# ═════════════════════════════════════════════════════════════════════
# SystemVerilog package generator
# ═════════════════════════════════════════════════════════════════════

def gen_sv_package(schema: dict[str, Any]) -> str:
    """Generate SystemVerilog package with localparam declarations."""
    lines: list[str] = []
    lines.append(f"// {GENERATED_MARKER}")
    lines.append(f"// ABI version: {schema['abi']['version_string']}")
    lines.append("")
    lines.append("package npu_abi_pkg;")
    lines.append("")
    lines.append(f"  // ABI version")
    lines.append(f"  localparam int unsigned NPU_ABI_MAJOR = {schema['abi']['major']};")
    lines.append(f"  localparam int unsigned NPU_ABI_MINOR = {schema['abi']['minor']};")
    lines.append("")

    # Address regions
    lines.append("  // ── Address Regions ───────────────────────────────────────")
    for name in sorted(schema["address_regions"]):
        reg = schema["address_regions"][name]
        base = int(reg["base"], 16)
        size = int(reg["size"], 16)
        lines.append(f"  localparam logic [31:0] NPU_{name}_BASE = 32'h{base:08X};")
        lines.append(f"  localparam logic [31:0] NPU_{name}_SIZE = 32'h{size:08X};")
    lines.append("")

    # Register offsets for each module
    for mod_name in sorted(schema["modules"]):
        mod = schema["modules"][mod_name]
        lines.append(f"  // ── {mod_name} Registers (NPU_{mod_name}_BASE) ─────────")
        for reg_name in sorted(mod["registers"]):
            reg = mod["registers"][reg_name]
            off = int(reg["offset"], 16)
            lines.append(f"  localparam logic [11:0] NPU_{mod_name}_{reg_name}_OFFSET = 12'h{off:03X};")
        lines.append("")

    # Opcodes
    lines.append("  // ── Engine Opcodes ────────────────────────────────────────")
    opcode_values = schema["opcodes"]["values"]
    for name in sorted(opcode_values, key=lambda n: opcode_values[n]["value"]):
        oc = opcode_values[name]
        lines.append(f"  localparam logic [7:0] NPU_ENGINE_OP_{name} = 8'h{oc['value']:02X};")
    lines.append("")

    # ISA opcodes
    lines.append("  // ── ISA Opcodes ───────────────────────────────────────────")
    isa_values = schema["isa_opcodes"]["values"]
    for name in sorted(isa_values, key=lambda n: isa_values[n]["value"]):
        oc = isa_values[name]
        lines.append(f"  localparam logic [4:0] NPU_ISA_OP_{name} = 5'h{oc['value']:02X};")
    lines.append("")

    # Status codes
    lines.append("  // ── Status Codes ──────────────────────────────────────────")
    for name in sorted(schema["status_codes"]["values"],
                        key=lambda n: schema["status_codes"]["values"][n]["value"]):
        sc = schema["status_codes"]["values"][name]
        lines.append(f"  localparam logic [31:0] NPU_STATUS_{name} = 32'h{sc['value']:08X};")
    lines.append("")

    # Capability bits
    lines.append("  // ── Capability Bits ───────────────────────────────────────")
    for name in sorted(schema["capability_bits"]["bits"],
                        key=lambda n: schema["capability_bits"]["bits"][n]["bit"]):
        cb = schema["capability_bits"]["bits"][name]
        lines.append(f"  localparam logic [31:0] NPU_CAP_{name} = 32'h{1 << cb['bit']:08X};")
    lines.append("")

    # INTC
    lines.append("  // ── Interrupt Source Bits ─────────────────────────────────")
    for name in sorted(schema["intc_mappings"]["sources"],
                        key=lambda n: schema["intc_mappings"]["sources"][n]["bit"]):
        src = schema["intc_mappings"]["sources"][name]
        lines.append(f"  localparam logic [6:0] NPU_INTC_{name}_BIT = 7'h{1 << src['bit']:02X};")
    lines.append("")

    # Ring configuration
    lines.append("  // ── Ring Buffer Configuration ─────────────────────────────")
    rc = schema["rings"]["configuration"]
    lines.append(f"  localparam int unsigned NPU_RING_ENTRIES = {rc['ring_entries']};")
    lines.append(f"  localparam int unsigned NPU_CMD_ENTRY_SIZE = {rc['cmd_entry_size']};")
    lines.append(f"  localparam int unsigned NPU_COMPLETION_ENTRY_SIZE = {rc['completion_entry_size']};")
    lines.append("")

    lines.append("endpackage : npu_abi_pkg")
    lines.append("")

    return "\n".join(lines)


# ═════════════════════════════════════════════════════════════════════
# Markdown documentation generator
# ═════════════════════════════════════════════════════════════════════

def gen_markdown(schema: dict[str, Any]) -> str:
    """Generate human-readable Markdown reference."""
    lines: list[str] = []
    lines.append(f"<!-- {GENERATED_MARKER} -->")
    lines.append("")
    lines.append(f"# CaduceusCore NPU ABI v{schema['abi']['version_string']}")
    lines.append("")
    lines.append(f"> **Endianness:** {schema['abi']['endianness']}-endian | "
                 f"**Register width:** {schema['abi']['register_width']}-bit | "
                 f"**Address granularity:** {schema['abi']['address_granularity']} bytes")
    lines.append("")
    lines.append("## Address Map")
    lines.append("")
    lines.append("| Region | Base | Size | Description |")
    lines.append("|--------|------|------|-------------|")
    for name in sorted(schema["address_regions"]):
        reg = schema["address_regions"][name]
        lines.append(f"| `{name}` | `{reg['base']}` | `{reg['size']}` | {reg['description']} |")
    lines.append("")

    # Each module
    for mod_name in sorted(schema["modules"]):
        mod = schema["modules"][mod_name]
        lines.append(f"## {mod_name}")
        lines.append(f"> **Base:** `{mod['base']}` | {mod.get('description', '')}")
        if "notes" in mod:
            for note in mod["notes"].values():
                lines.append(f"> ⚠️ {note}")
        lines.append("")
        lines.append("| Offset | Register | Access | Reset | Description |")
        lines.append("|--------|----------|--------|-------|-------------|")
        for reg_name in sorted(mod["registers"]):
            reg = mod["registers"][reg_name]
            arr = f"[{reg['array_size']}]" if reg.get("array_size") else ""
            lines.append(f"| `{reg['offset']}` | `{reg_name}{arr}` | {reg['access']} | `{reg['reset']}` | {reg.get('description', '')} |")
        lines.append("")

    # Opcodes
    lines.append("## Engine Opcodes (Firmware Dispatch)")
    lines.append("")
    lines.append("| Name | Value | Engine | Description |")
    lines.append("|------|-------|--------|-------------|")
    opcode_values = schema["opcodes"]["values"]
    for name in sorted(opcode_values, key=lambda n: opcode_values[n]["value"]):
        oc = opcode_values[name]
        lines.append(f"| `{name}` | `{oc['value']:#04x}` | {oc['engine']} | {oc['description']} |")
    lines.append("")

    lines.append("## ISA Opcodes")
    lines.append("")
    lines.append("| Name | Value (5-bit) | Description |")
    lines.append("|------|---------------|-------------|")
    isa_values = schema["isa_opcodes"]["values"]
    for name in sorted(isa_values, key=lambda n: isa_values[n]["value"]):
        oc = isa_values[name]
        lines.append(f"| `{name}` | `{oc['value']:#04x}` | {oc['description']} |")
    lines.append("")

    # Status codes
    lines.append("## Status Codes")
    lines.append("")
    lines.append("| Name | Value | Description |")
    lines.append("|------|-------|-------------|")
    for name in sorted(schema["status_codes"]["values"],
                        key=lambda n: schema["status_codes"]["values"][n]["value"]):
        sc = schema["status_codes"]["values"][name]
        lines.append(f"| `{name}` | {sc['value']} | {sc['description']} |")
    lines.append("")

    # Descriptors
    for desc_name in sorted(schema["descriptors"]):
        if desc_name == "description":
            continue
        desc = schema["descriptors"][desc_name]
        lines.append(f"## {desc_name} Descriptor ({desc['packed_size']} bytes)")
        if "notes" in desc:
            for note in desc["notes"]:
                lines.append(f"> {note}")
        lines.append("")
        lines.append("| Index | Offset | Field | Type | Description |")
        lines.append("|-------|--------|-------|------|-------------|")
        for f in desc["fields"]:
            lines.append(f"| {f['index']} | {f['offset']} | `{f['name']}` | {f['type']} | {f['description']} |")
        lines.append("")

    # Compatibility rules
    lines.append("## Compatibility")
    lines.append("")
    lines.append(f"- **Major version bump** ({schema['abi']['major']}): {schema['abi']['compatibility']['major_break']}")
    lines.append(f"- **Minor version bump** ({schema['abi']['major']}.x): {schema['abi']['compatibility']['minor_add']}")
    lines.append("")

    # Known discrepancies
    if "known_discrepancies" in schema:
        lines.append("## Known Discrepancies")
        lines.append("")
        for item in schema["known_discrepancies"]["items"]:
            sev = item["severity"].upper()
            lines.append(f"### {item['id']} [{sev}]")
            lines.append(f"{item['description']}")
            lines.append("")
            lines.append(f"**Sources:** {', '.join(item['sources'])}")
            lines.append("")

    return "\n".join(lines)


# ═════════════════════════════════════════════════════════════════════
# Generator dispatch
# ═════════════════════════════════════════════════════════════════════

GENERATORS = {
    "gen/npu_abi.py":             gen_python,
    "gen/npu_abi.h":              gen_c_header,
    "gen/npu_abi_firmware.h":     gen_firmware_header,
    "gen/npu_abi_pkg.sv":         gen_sv_package,
    "gen/npu_abi.md":             gen_markdown,
}


def generate_all(schema: dict[str, Any], out_dir: Path) -> list[Path]:
    """Generate all artifacts into out_dir. Returns list of paths written."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for rel_path, gen_fn in sorted(GENERATORS.items()):
        content = gen_fn(schema)
        target = out_dir / Path(rel_path).name
        target.write_text(content, encoding="utf-8")
        written.append(target)
    return written


def check_artifacts(schema: dict[str, Any]) -> bool:
    """Generate into temp dir, compare with existing files. Returns True if all match."""
    repo_gen = REPO / "gen"
    with tempfile.TemporaryDirectory(prefix="npu_abi_check_") as tmp:
        tmp_dir = Path(tmp)
        generate_all(schema, tmp_dir)
        all_ok = True
        for rel_path in sorted(GENERATORS):
            target_name = Path(rel_path).name
            existing = repo_gen / target_name
            generated = tmp_dir / target_name
            if not existing.is_file():
                print(f"  MISSING: {target_name}")
                all_ok = False
                continue
            if not filecmp.cmp(str(existing), str(generated), shallow=False):
                print(f"  MISMATCH: {target_name}")
                all_ok = False
            else:
                print(f"  OK: {target_name}")
    return all_ok


# ═════════════════════════════════════════════════════════════════════
# CLI
# ═════════════════════════════════════════════════════════════════════

def main() -> None:
    parser = argparse.ArgumentParser(
        description="NPU ABI Schema Generator — deterministic bindings from spec/npu_abi.json"
    )
    parser.add_argument(
        "--generate", action="store_true",
        help="Generate all artifacts into gen/ directory"
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Verify generated artifacts match schema (exit 0 on match, 1 on mismatch)"
    )
    args = parser.parse_args()

    if not args.generate and not args.check:
        parser.print_help()
        sys.exit(2)

    schema = load_schema()

    if args.check:
        print(f"Checking ABI v{schema['abi']['version_string']} generated artifacts...")
        ok = check_artifacts(schema)
        if ok:
            print(f"✅ All generated artifacts match the schema.")
            sys.exit(0)
        else:
            print(f"❌ Generated artifacts are out of date. Run --generate to update.")
            sys.exit(1)

    if args.generate:
        out_dir = REPO / "gen"
        print(f"Generating ABI v{schema['abi']['version_string']} artifacts into {out_dir}/ ...")
        written = generate_all(schema, out_dir)
        for p in written:
            print(f"  {p.name}")
        print(f"✅ {len(written)} artifacts generated.")


if __name__ == "__main__":
    main()
