#!/usr/bin/env bash
# =============================================================================
# p10_f3_manual_qa.sh — Phase 10 Final Wave F3: Real manual QA
# =============================================================================
# Independently reproduces, on sz0001, the three key Phase 10 evidences and
# runs a sha256 integrity check over all task evidence files:
#
#   1. DMA readback fix (todo 5)   — COCOTB_BRIDGE_DIAG_DMA default-off probe
#                                    check + `make run_e2e_dma_load` PASS +
#                                    PERF p0 sample PASS (covered by the PERF-06
#                                    batch stage below).
#   2. PERF-06 causality gate (todo 9) — full 6-batch PERF regression on
#                                    sz0001, gated on 21/21 PASS with
#                                    PERF-06 cos_sim >= 0.999, plus the
#                                    testcase-list sync state check.
#   3. 36-layer Ibex segment run (todo 13) — the 9-layer checkpoint subset
#                                    (L0 | L9->L10 | L19->L20 | L29->L30 |
#                                    L34->L35) re-run via
#                                    scripts/p10_36layer_ibex.sh; asserts
#                                    chain_restart_state_source=ibex_dram and
#                                    the tolerance ladder.  The full 36-layer
#                                    Ibex run is OUT of scope (deferred to the
#                                    FPGA phase).
#   4. sha256 manifest — all build/evidence/task-*-phase10-rtl-verification.txt
#                                    files (excluding this task-F3 file itself,
#                                    which is regenerated by every F3 run) are
#                                    hashed and verified against the recorded
#                                    manifest build/evidence/
#                                    ph10-task-evidence-manifest.sha256.
#                                    First run bootstraps the manifest.
#
# Evidence integrity: the PERF batches write their JSONL results into
# build/evidence/{w4-perf-p*,fullchain-pipeline}.txt by design.  F3 saves the
# committed copies first, parses the fresh reproduction results, then restores
# the committed copies and verifies the restore is bit-exact — so NO evidence
# file is modified by the end of a run.  The task-* evidence files are checked
# before and after the reproductions; any modification (other than task-13,
# which the mandated re-run of scripts/p10_36layer_ibex.sh regenerates) fails
# the run.
#
# Exit codes:
#   0  all three key evidences reproducible + manifest match/bootstrap
#   1  any reproduction FAIL or manifest mismatch/tamper
#
# Usage (from repo root, on sz0002; drives sz0001 via p10_ssh):
#   bash scripts/p10_f3_manual_qa.sh
# =============================================================================
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/p10_lib/p10_sz0001.sh"

ROOT="$REPO_ROOT"
EVID="$ROOT/build/evidence"
F3_EVID="$EVID/task-F3-phase10-rtl-verification.txt"
MANIFEST="$EVID/ph10-task-evidence-manifest.sha256"
SIMV="$ROOT/build/ibex_full_rtl/simv_soc_ibex"
FW_HEX="$ROOT/firmware/build/npu_firmware.hex"
TC_LIST="$ROOT/rtl/testcase-list-perf.md"
IBEX_SCRIPT="$ROOT/scripts/p10_36layer_ibex.sh"

STAGE_TIMEOUT="${P10_F3_STAGE_TIMEOUT:-2400}"
IBEX_TIMEOUT="${P10_F3_IBEX_TIMEOUT:-21600}"
COMMIT="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo "?")"
TS_START="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

F3_TMP="$(mktemp -d /tmp/p10_f3_qa.XXXXXX)"
EVIDENCE_WRITTEN=0
F3_FAIL=0

mkdir -p "$EVID"

log()  { echo "[p10_f3] $*"; }
fail() { F3_FAIL=1; echo "[p10_f3] FAIL: $*"; }

# Guarantee an evidence file exists even on interruption.
trap 'if [ "$EVIDENCE_WRITTEN" = "0" ]; then
  {
    echo "Phase 10 Final Wave F3 - Real manual QA: INCOMPLETE"
    echo "=================================================="
    echo "Timestamp : $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "Commit    : ${COMMIT:-?}"
    echo "Status    : interrupted before final evidence write"
    echo "Logs      : build/evidence/task-F3-*.log"
  } > "${F3_EVID}" 2>/dev/null || true
fi
rm -rf "${F3_TMP}"' EXIT

# =============================================================================
# Remote stage runner (setsid + detached watchdog, no stray simv on SSH drop)
# =============================================================================
run_remote_stage() {
  local name="$1" timeout_s="$2" logfile="$3" body="$4"
  local stage_rc ssh_rc
  log "Stage ${name}: start ($(date -u +%Y-%m-%dT%H:%M:%SZ), timeout=${timeout_s}s)" >&2
  body=${body//__ROOT__/$ROOT}
  local remote_cmd
  remote_cmd="set +e
TMPSTAGE=/tmp/p10f3_${name}_\$\$.sh
cat > \"\$TMPSTAGE\" <<'STAGE_EOF'
${body}
STAGE_EOF
setsid bash \"\$TMPSTAGE\" &
SPID=\$!
setsid bash -c 'sleep ${timeout_s}; kill -TERM -\$1 2>/dev/null; sleep 10; kill -KILL -\$1 2>/dev/null' _ \$SPID </dev/null >/dev/null 2>&1 &
KILLER=\$!
wait \$SPID
rc=\$?
kill -TERM -\$KILLER 2>/dev/null
sleep 1
kill -KILL -\$KILLER 2>/dev/null
echo \"STAGE_EXIT=\$rc\"
rm -f \"\$TMPSTAGE\"
exit 0"
  p10_ssh "$remote_cmd" > "$logfile" 2>&1
  ssh_rc=$?
  stage_rc=$(grep -oE '^STAGE_EXIT=[0-9]+' "$logfile" | tail -1 | cut -d= -f2)
  [ -n "$stage_rc" ] || stage_rc="ssh-error-${ssh_rc}"
  log "Stage ${name}: done (STAGE_EXIT=${stage_rc})" >&2
  echo "$stage_rc"
}

# =============================================================================
# Phase 0 — Preconditions (firmware hex + simv on sz0001)
# =============================================================================
log "=== Phase 0: preconditions ==="
PRE_OK=1
[ -f "$FW_HEX" ] || { fail "firmware hex missing: $FW_HEX"; PRE_OK=0; }
if [ "$PRE_OK" = "1" ] && ! p10_ssh "test -x '${SIMV}'" 2>/dev/null; then
  log "  simv_soc_ibex missing on sz0001 — rebuilding via run_ibex_full_rtl.sh..."
  p10_ssh "bash sim/regression/run_ibex_full_rtl.sh FM-SOC-001" || {
    fail "cannot compile simv_soc_ibex"; PRE_OK=0; }
  p10_ssh "test -x '${SIMV}'" || { fail "simv still missing after rebuild"; PRE_OK=0; }
else
  log "  simv_soc_ibex: OK (sz0001)"
fi
[ "$PRE_OK" = "1" ] && log "  firmware hex: OK"

# =============================================================================
# Phase 1 — Manifest pre-check (tamper detection vs recorded manifest)
# =============================================================================
log "=== Phase 1: manifest pre-check ==="
MANIFEST_PRE="NONE"
if [ -f "$MANIFEST" ]; then
  if (cd "$EVID" && sha256sum -c "$(basename "$MANIFEST")" > "$F3_TMP/manifest_pre.log" 2>&1); then
    MANIFEST_PRE="PASS"
    log "  recorded manifest verifies against current evidence: PASS"
  else
    MANIFEST_PRE="MISMATCH"
    fail "recorded manifest does NOT match current evidence (tamper?):"
    cat "$F3_TMP/manifest_pre.log" | grep -E 'FAILED|missing' | head -10 || true
  fi
else
  log "  no recorded manifest yet — first F3 run will bootstrap it"
fi

# Snapshot pre-run hashes of all task-* evidence files (excl. task-F3).
# Bare filenames (no ./ prefix) so the classifier compares like-for-like.
(cd "$EVID" && ls task-*-phase10-rtl-verification.txt 2>/dev/null \
    | grep -v '^task-F3-' | xargs -r sha256sum) > "$F3_TMP/pre.sha256" 2>/dev/null || true

# =============================================================================
# Phase 2 — DMA readback fix reproduction (todo 5)
# =============================================================================
log "=== Phase 2: DMA readback fix (todo 5) ==="
DMA_STATIC_OK=1
DMA_E2E_OK=1
DMA_PERF_SAMPLE_OK="pending"

# 2a. COCOTB_BRIDGE_DIAG_DMA must be default-off (todo 5 commit b158180).
if grep -q 'COCOTB_BRIDGE_DIAG_DMA", "0"' "$ROOT/sim/cocotb_bridge.py"; then
  log "  DIAG_DMA probe default-off: PASS (sim/cocotb_bridge.py)"
else
  fail "DIAG_DMA probe is NOT default-off in sim/cocotb_bridge.py"
  DMA_STATIC_OK=0
fi

# 2b. make run_e2e_dma_load (test_e2e_dma_load_store on tb_soc) on sz0001.
DMA_E2E_LOG="$EVID/task-F3-dma-e2e.log"
log "  running make run_e2e_dma_load on sz0001..."
DMA_E2E_BODY=$(cat <<'STAGE_EOF'
set -euo pipefail
cd __ROOT__
make -C sim/regression run_e2e_dma_load
STAGE_EOF
)
DMA_E2E_RC=$(run_remote_stage dma_e2e 1800 "$DMA_E2E_LOG" "$DMA_E2E_BODY")
if [ "$DMA_E2E_RC" = "0" ] && grep -qE 'E2E_DMA_LOAD: PASS|test_e2e_dma_load_store.*PASS' "$DMA_E2E_LOG"; then
  log "  test_e2e_dma_load_store: PASS"
else
  fail "test_e2e_dma_load_store FAILED (rc=${DMA_E2E_RC}); see ${DMA_E2E_LOG}"
  DMA_E2E_OK=0
  tail -20 "$DMA_E2E_LOG" || true
fi

# 2c. PERF p0 sample (todo 5 verification) — executed as batch 1 of Phase 3.

# =============================================================================
# Phase 3 — PERF-06 causality gate reproduction (todo 9)
# =============================================================================
log "=== Phase 3: PERF-06 causality gate (todo 9) ==="
BATCHES=(
  "test_w4_perf_p0|w4-perf-p0.txt|P0 Infrastructure (PERF-01..04)"
  "test_w4_perf_p1|w4-perf-p1.txt|P1 Multi-Tile Baseline (PERF-05..08)"
  "test_w4_perf_p2|w4-perf-p2.txt|P2 Weight Streaming (PERF-09..12)"
  "test_w4_perf_p3|w4-perf-p3.txt|P3 All MMULs + Chain (PERF-13..16)"
  "test_w4_perf_p4|w4-perf-p4.txt|P4 Deep Analysis (PERF-17..20)"
  "test_w4_perf_fullchain|fullchain-pipeline.txt|FULLCHAIN pipeline"
)
PERF_FILES=(w4-perf-p0.txt w4-perf-p1.txt w4-perf-p2.txt w4-perf-p3.txt w4-perf-p4.txt fullchain-pipeline.txt)

# Save the committed PERF evidence copies (restored bit-exact after parsing).
mkdir -p "$F3_TMP/saved"
for f in "${PERF_FILES[@]}"; do
  if [ -f "$EVID/$f" ]; then cp -p "$EVID/$f" "$F3_TMP/saved/$f"; fi
done
(cd "$F3_TMP/saved" && sha256sum "${PERF_FILES[@]}" > "$F3_TMP/saved.sha256" 2>/dev/null) || true

make_batch_body() {
  cat <<'STAGE_EOF'
set -euo pipefail
export PYTHONPATH="${PYTHONPATH:-}:__ROOT__"
export MODULE=sim.perf_tests
export TOPLEVEL=tb_soc_ibex
export TOPLEVEL_LANG=verilog
export FM_SOC_RTL_MODE=ibex
export BOOTROM_HEX="__ROOT__/firmware/build/npu_firmware.hex"
export TESTCASE=__TESTCASE__
cd "$(cd __ROOT__/.. && pwd)"
echo "[p10_f3] Running __TESTCASE__ ..."
"__ROOT__/build/ibex_full_rtl/simv_soc_ibex" +COCOTB +BOOTROM_HEX="$BOOTROM_HEX"
echo "[p10_f3] __TESTCASE__ done."
STAGE_EOF
}

STAGE_RCS=""
for BATCH_ENTRY in "${BATCHES[@]}"; do
  IFS='|' read -r TESTCASE EVFILE DESC <<< "${BATCH_ENTRY}"
  echo ""
  echo "── ${TESTCASE} — ${DESC} ──"
  BODY="$(make_batch_body)"
  BODY=${BODY//__TESTCASE__/$TESTCASE}
  STAGELOG="$F3_TMP/stage-${TESTCASE}.log"
  RC=$(run_remote_stage "${TESTCASE}" "$STAGE_TIMEOUT" "$STAGELOG" "$BODY")
  STAGE_RCS="${STAGE_RCS} ${TESTCASE}=${RC}"
  if [ "$RC" != "0" ]; then
    fail "stage ${TESTCASE} exited ${RC}; see log tail:"
    tail -15 "$STAGELOG" || true
  fi
  sleep 3  # let NFS flush the JSONL evidence files before parsing
done

# Parse the fresh reproduction results (all 21 cases PASS, cos_sim >= 0.999).
PERF_PARSE_OK=1
P10F3_EVID="$EVID" P10F3_RESULTS="$F3_TMP/results.tsv" python3 <<'PYEOF'
import json
import os
import sys

EVID = os.environ["P10F3_EVID"]
OUT = os.environ["P10F3_RESULTS"]

expected = {
    "w4-perf-p0.txt": ["PERF-01", "PERF-02", "PERF-03", "PERF-04"],
    "w4-perf-p1.txt": ["PERF-05", "PERF-06", "PERF-07", "PERF-08"],
    "w4-perf-p2.txt": ["PERF-09", "PERF-10", "PERF-11", "PERF-12"],
    "w4-perf-p3.txt": ["PERF-13", "PERF-14", "PERF-15", "PERF-16"],
    "w4-perf-p4.txt": ["PERF-17", "PERF-18", "PERF-19", "PERF-20"],
    "fullchain-pipeline.txt": ["FULLCHAIN"],
}

rows = []
problems = []
for fname, cids in expected.items():
    path = os.path.join(EVID, fname)
    by_id = {}
    if os.path.isfile(path):
        for line in open(path, encoding="utf-8"):
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            try:
                d = json.loads(line)
            except Exception:
                continue
            cid = d.get("case_id")
            if cid:
                by_id[cid] = d
    for cid in cids:
        d = by_id.get(cid)
        if d is None:
            rows.append((cid, "MISSING", "-", "-", fname))
            problems.append(f"{cid}: missing in {fname}")
            continue
        st = str(d.get("status", "?"))
        cs = d.get("cos_sim")
        cs_s = ("%.6f" % float(cs)) if isinstance(cs, (int, float)) else "-"
        cyc = str(d.get("cycles", "-"))
        rows.append((cid, st, cs_s, cyc, fname))
        if st != "PASS":
            problems.append(f"{cid}: status={st} in {fname}")
        elif cs_s != "-" and float(cs) < 0.999:
            problems.append(f"{cid}: cos_sim={cs_s} < 0.999 in {fname}")

with open(OUT, "w", encoding="utf-8") as f:
    for r in rows:
        f.write("\t".join(r) + "\n")

print(f"[p10_f3] parsed {len(rows)} fresh PERF cases")
if problems:
    print("PROBLEMS:")
    for p in problems:
        print("  " + p)
    sys.exit(1)
print("[p10_f3] all fresh PERF cases PASS (cos_sim >= 0.999 where applicable)")
PYEOF
PERF_PARSE_OK=$?
TOTAL=$(wc -l < "$F3_TMP/results.tsv" | tr -d ' ')
PERF06_CS=$(awk -F'\t' '$1=="PERF-06" {print $3}' "$F3_TMP/results.tsv")
PERF06_ST=$(awk -F'\t' '$1=="PERF-06" {print $2}' "$F3_TMP/results.tsv")
P0_SAMPLE_CS=$(awk -F'\t' '$1=="PERF-01" || $1=="PERF-02" || $1=="PERF-03" || $1=="PERF-04" {print $3}' "$F3_TMP/results.tsv" | tr '\n' ' ')

if [ "$PERF_PARSE_OK" -ne 0 ] || [ "$TOTAL" != "21" ] \
   || [ "$PERF06_ST" != "PASS" ] || ! python3 -c "import sys; sys.exit(0 if float('${PERF06_CS:-0}') >= 0.999 else 1)"; then
  fail "PERF reproduction NOT green: parsed=${TOTAL}/21 PERF-06 status=${PERF06_ST:-?} cos_sim=${PERF06_CS:-parse-error}"
else
  log "  PERF reproduction: ${TOTAL}/21 PASS, PERF-06 cos_sim=${PERF06_CS}"
fi

# todo-5 PERF p0 sample (batch 1) verdict.
if [ "$PERF_PARSE_OK" -eq 0 ]; then
  DMA_PERF_SAMPLE_OK="PASS"
  log "  todo-5 PERF p0 sample: PASS (PERF-01..04 all PASS)"
else
  DMA_PERF_SAMPLE_OK="FAIL"
fi

# testcase-list sync state (static, committed by todo 9).
if grep -q 'Phase 10 状态: PASS 21 | NOT RESOLVED 0' "$TC_LIST" \
   && grep -qE '^\| PERF-06 \|.*\| ✅ PASS \|' "$TC_LIST"; then
  TC_SYNC_OK=1
  log "  testcase-list: 21/21 PASS, stats line synced (rtl/testcase-list-perf.md)"
else
  fail "testcase-list not synced (PERF-06 row or stats line missing)"
  TC_SYNC_OK=0
fi

# Restore the committed PERF evidence copies and verify bit-exact restore.
for f in "${PERF_FILES[@]}"; do
  if [ -f "$F3_TMP/saved/$f" ]; then cp -p "$F3_TMP/saved/$f" "$EVID/$f"; else rm -f "$EVID/$f"; fi
done
sleep 1
if (cd "$EVID" && sha256sum -c "$F3_TMP/saved.sha256" > "$F3_TMP/restore.log" 2>&1); then
  log "  PERF evidence restored bit-exact (committed copies intact)"
else
  fail "PERF evidence restore NOT bit-exact!"
  cat "$F3_TMP/restore.log" | grep -E 'FAILED' || true
fi

# =============================================================================
# Phase 4 — Ibex 36-layer checkpoint-subset segment run (todo 13)
# =============================================================================
log "=== Phase 4: Ibex segment run (todo 13, 9-layer checkpoint subset) ==="
IBEX_OK=1
IBEX_RC="skipped"
IBEX_LOG="$EVID/task-F3-ibex.log"
# Concurrency guard: run_ibex_segment_run.sh exits via `pkill -f
# simv_soc_ibex_seg`, which would kill an unrelated concurrent segment run.
if p10_ssh "pgrep -f simv_soc_ibex_seg" >/dev/null 2>&1; then
  fail "another simv_soc_ibex_seg is running on sz0001 — refusing to overlap (re-run F3 after it finishes)"
  IBEX_OK=0
else
  log "  running bash scripts/p10_36layer_ibex.sh (timeout=${IBEX_TIMEOUT}s)..."
  timeout "$IBEX_TIMEOUT" bash "$IBEX_SCRIPT" > "$IBEX_LOG" 2>&1
  IBEX_RC=$?
  if [ "$IBEX_RC" -ne 0 ]; then
    fail "p10_36layer_ibex.sh exited ${IBEX_RC} (log: ${IBEX_LOG})"
    tail -30 "$IBEX_LOG" || true
    IBEX_OK=0
  elif grep -q 'ALL ASSERTIONS PASS' "$IBEX_LOG"; then
    log "  p10_36layer_ibex.sh: ALL ASSERTIONS PASS"
  else
    fail "p10_36layer_ibex.sh rc=0 but assertions not confirmed in log"
    IBEX_OK=0
  fi
fi

# Independent re-verification of the todo-13 evidence fields (only when the
# segment run was actually attempted; the concurrency guard already records
# its own FAIL otherwise).
T13_EVID="$EVID/task-13-phase10-rtl-verification.txt"
if [ "$IBEX_RC" = "skipped" ]; then
  :  # guard already recorded the FAIL
elif [ ! -f "$T13_EVID" ]; then
  fail "task-13 evidence missing after segment run: $T13_EVID"
  IBEX_OK=0
else
  for field in "engine=ibex" "ibex_executed=L0,L9,L10,L19,L20,L29,L30,L34,L35" \
               "checkpoints=L0,L10,L20,L30,L35" "chain_restart=true" \
               "chain_restart_state_source=ibex_dram" "segment_input_source=spike_npz" \
               "LADDER=PASS"; do
    grep -qF "$field" "$T13_EVID" \
      && log "  evidence field OK   : $field" \
      || { fail "evidence field missing: $field"; IBEX_OK=0; }
  done
fi

# =============================================================================
# Phase 5 — Manifest post-check + record + final evidence
# =============================================================================
log "=== Phase 5: manifest post-check ==="
(cd "$EVID" && ls task-*-phase10-rtl-verification.txt 2>/dev/null \
    | grep -v '^task-F3-' | xargs -r sha256sum) > "$F3_TMP/post.sha256" 2>/dev/null || true

MANIFEST_CLASSIFY="$(P10F3_PRE="$F3_TMP/pre.sha256" P10F3_POST="$F3_TMP/post.sha256" python3 <<'PYEOF'
import os
import sys

def load(p):
    d = {}
    if os.path.isfile(p):
        for line in open(p, encoding="utf-8"):
            line = line.strip()
            if line:
                parts = line.split(None, 1)
                if len(parts) == 2:
                    d[parts[1]] = parts[0]
    return d

pre = load(os.environ["P10F3_PRE"])
post = load(os.environ["P10F3_POST"])
added = sorted(set(post) - set(pre))
removed = sorted(set(pre) - set(post))
changed = sorted(f for f in set(pre) & set(post) if pre[f] != post[f])
print(f"added={','.join(added) or '-'}")
print(f"removed={','.join(removed) or '-'}")
print(f"changed={','.join(changed) or '-'}")
PYEOF
)"
MANIFEST_ADDED=$(echo "$MANIFEST_CLASSIFY" | grep '^added=' | cut -d= -f2-)
MANIFEST_REMOVED=$(echo "$MANIFEST_CLASSIFY" | grep '^removed=' | cut -d= -f2-)
MANIFEST_CHANGED=$(echo "$MANIFEST_CLASSIFY" | grep '^changed=' | cut -d= -f2-)
log "  manifest diff: added=[${MANIFEST_ADDED}] removed=[${MANIFEST_REMOVED}] changed=[${MANIFEST_CHANGED}]"

MANIFEST_TAMPER=0
# Removed files are always a failure (evidence deleted during reproduction).
[ "$MANIFEST_REMOVED" = "-" ] || { fail "task evidence removed during run: ${MANIFEST_REMOVED}"; MANIFEST_TAMPER=1; }
# Changed files: only task-13 is tolerated, and only when the Ibex phase
# (which regenerates it) passed.
if [ "$MANIFEST_CHANGED" != "-" ]; then
  for f in ${MANIFEST_CHANGED//,/ }; do
    if [ "$f" = "task-13-phase10-rtl-verification.txt" ] && [ "$IBEX_OK" = "1" ]; then
      log "  task-13 evidence regenerated by the F3 Ibex reproduction (expected)"
    else
      fail "task evidence modified during run: $f"
      MANIFEST_TAMPER=1
    fi
  done
fi
# Unexpected additions (other than task-13 created by the Ibex reproduction).
if [ "$MANIFEST_ADDED" != "-" ]; then
  for f in ${MANIFEST_ADDED//,/ }; do
    if [ "$f" = "task-13-phase10-rtl-verification.txt" ] && [ "$IBEX_OK" = "1" ]; then
      log "  task-13 evidence created by the F3 Ibex reproduction (expected)"
    else
      log "  NOTE: new task evidence appeared: $f (recorded in manifest)"
    fi
  done
fi

# Write/refresh the canonical manifest.
(cd "$EVID" && ls task-*-phase10-rtl-verification.txt 2>/dev/null \
    | grep -v '^task-F3-' | xargs -r sha256sum) > "$MANIFEST"
MANIFEST_COUNT=$(wc -l < "$MANIFEST" | tr -d ' ')

if [ "$MANIFEST_PRE" = "NONE" ]; then
  MANIFEST_STATUS="RECORDED (bootstrap: first F3 run)"
  log "  manifest recorded (bootstrap): ${MANIFEST_COUNT} files"
elif [ "$MANIFEST_PRE" = "MISMATCH" ] || [ "$MANIFEST_TAMPER" = "1" ]; then
  MANIFEST_STATUS="MISMATCH"
else
  if [ "$MANIFEST_CHANGED" = "-" ] && [ "$MANIFEST_ADDED" = "-" ] && [ "$MANIFEST_REMOVED" = "-" ]; then
    MANIFEST_STATUS="MATCH (no evidence changed)"
    log "  manifest matches recorded state: ${MANIFEST_COUNT} files"
  else
    MANIFEST_STATUS="UPDATED (task-13 regenerated by F3 reproduction)"
    log "  manifest re-recorded: ${MANIFEST_COUNT} files"
  fi
fi

# =============================================================================
# Verdict
# =============================================================================
TS_END="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
DMA_OK=1
[ "$DMA_STATIC_OK" = "1" ] && [ "$DMA_E2E_OK" = "1" ] && [ "$DMA_PERF_SAMPLE_OK" = "PASS" ] || DMA_OK=0
PERF06_OK=1
[ "$PERF_PARSE_OK" = "0" ] && [ "$TOTAL" = "21" ] && [ "$PERF06_ST" = "PASS" ] && [ "$TC_SYNC_OK" = "1" ] || PERF06_OK=0
MANIFEST_OK=1
[ "$MANIFEST_STATUS" = "MISMATCH" ] && MANIFEST_OK=0
[ "$MANIFEST_PRE" = "MISMATCH" ] && MANIFEST_OK=0
[ "$MANIFEST_TAMPER" = "1" ] && MANIFEST_OK=0

VERDICT="PASS"
if [ "$F3_FAIL" -ne 0 ] || [ "$DMA_OK" -ne 1 ] || [ "$PERF06_OK" -ne 1 ] \
   || [ "$IBEX_OK" -ne 1 ] || [ "$MANIFEST_OK" -ne 1 ]; then
  VERDICT="FAIL"
fi

{
  echo "Phase 10 Final Wave F3 - Real manual QA: independent reproduction of key evidences"
  echo "=================================================================================="
  echo "Timestamp start : ${TS_START}"
  echo "Timestamp end   : ${TS_END}"
  echo "Commit          : ${COMMIT}"
  echo "Driver host     : $(hostname) (sz0002) — all simulations executed on sz0001"
  echo "                  via p10_ssh (ssh ${ZHENGS}@${SZ0001})"
  echo "Script          : scripts/p10_f3_manual_qa.sh"
  echo ""
  echo "Scope: independent re-run of the three key Phase 10 RTL evidences plus a"
  echo "sha256 integrity check over all task evidence files."
  echo "  1. DMA readback fix (todo 5)"
  echo "  2. PERF-06 causality gate (todo 9): full 6-batch PERF regression, 21/21"
  echo "  3. 36-layer Ibex checkpoint-subset segment run (todo 13): 9 layers,"
  echo "     L0 | L9->L10 | L19->L20 | L29->L30 | L34->L35, 5 checkpoints"
  echo "  4. sha256 manifest of build/evidence/task-*-phase10-rtl-verification.txt"
  echo "     (task-F3 itself excluded; regenerated by every F3 run)"
  echo "Out of scope: full 36-layer Ibex run (deferred to the FPGA phase)."
  echo ""
  echo "── 1. DMA readback fix (todo 5) ─────────────────────────────────────────"
  echo "  COCOTB_BRIDGE_DIAG_DMA default-off : $([ "$DMA_STATIC_OK" = "1" ] && echo PASS || echo FAIL)"
  echo "  make run_e2e_dma_load (sz0001)     : $([ "$DMA_E2E_OK" = "1" ] && echo PASS || echo FAIL)"
  echo "    log: build/evidence/task-F3-dma-e2e.log (rc=${DMA_E2E_RC})"
  echo "  PERF p0 sample (todo-5 check)      : ${DMA_PERF_SAMPLE_OK} (PERF-01..04)"
  echo "  Reproduction verdict               : $([ "$DMA_OK" = "1" ] && echo PASS || echo FAIL)"
  echo ""
  echo "── 2. PERF-06 causality gate (todo 9) ───────────────────────────────────"
  echo "  Fresh PERF reproduction results (6 batches on sz0001, from"
  echo "  simv_soc_ibex + firmware/build/npu_firmware.hex):"
  while IFS=$'\t' read -r cid st cs cyc fname; do
    [ -n "$cid" ] || continue
    printf '    %-12s %-6s cos_sim=%-10s cycles=%-8s evidence=%s\n' "$cid" "$st" "$cs" "$cyc" "$fname"
  done < "$F3_TMP/results.tsv" 2>/dev/null || echo "    (no results.tsv)"
  echo "  PERF-06 cos_sim>=0.999            : $([ "$PERF06_ST" = "PASS" ] && echo "PASS (cos_sim=${PERF06_CS})" || echo FAIL)"
  echo "  testcase-list: 21/21 PASS          : $([ "$TC_SYNC_OK" = "1" ] && echo PASS || echo FAIL)"
  echo "    PERF-06 row ✅ PASS + 'Phase 10 状态: PASS 21 | NOT RESOLVED 0' in"
  echo "    rtl/testcase-list-perf.md; committed task-9 evidence states"
  echo "    'PERF-06 cos_sim>=0.999: PASS' and 'stats-line-synced: true'."
  echo "  PERF evidence files               : committed copies saved before the"
  echo "    batches, restored bit-exact after parsing (no evidence modified)."
  echo "  Stage exit codes                  :${STAGE_RCS}"
  echo "  Reproduction verdict              : $([ "$PERF06_OK" = "1" ] && echo PASS || echo FAIL)"
  echo ""
  echo "── 3. Ibex segment run (todo 13, 9-layer checkpoint subset) ─────────────"
  echo "  Command          : timeout ${IBEX_TIMEOUT} bash scripts/p10_36layer_ibex.sh"
  echo "  Exit code        : ${IBEX_RC}"
  echo "  Log              : build/evidence/task-F3-ibex.log"
  echo "  Evidence         : build/evidence/task-13-phase10-rtl-verification.txt"
  echo "  Key fields       : engine=ibex / ibex_executed=L0,L9,L10,L19,L20,L29,L30,L34,L35"
  echo "                     checkpoints=L0,L10,L20,L30,L35 / chain_restart=true"
  echo "                     chain_restart_state_source=ibex_dram /"
  echo "                     segment_input_source=spike_npz / LADDER=PASS"
  if [ -f "$T13_EVID" ]; then
    echo "  Checkpoint results (from reproduced evidence):"
    grep -E '^layer=.*engine=ibex cos_sim=' "$T13_EVID" | sed 's/^/    /' || true
  fi
  echo "  Reproduction verdict              : $([ "$IBEX_OK" = "1" ] && echo PASS || echo FAIL)"
  echo ""
  echo "── 4. sha256 manifest ───────────────────────────────────────────────────"
  echo "  Manifest         : build/evidence/ph10-task-evidence-manifest.sha256"
  echo "  Files covered    : ${MANIFEST_COUNT} (task-F3 excluded)"
  echo "  Pre-run check    : ${MANIFEST_PRE} (vs recorded manifest)"
  echo "  Post-run diff    : added=[${MANIFEST_ADDED}] removed=[${MANIFEST_REMOVED}] changed=[${MANIFEST_CHANGED}]"
  echo "  Manifest status  : ${MANIFEST_STATUS}"
  echo "  Verdict          : $([ "$MANIFEST_OK" = "1" ] && echo PASS || echo FAIL)"
  echo ""
  echo "── Cleanup receipt ──────────────────────────────────────────────────────"
  STRAY_CHECK=$(p10_ssh "pgrep -af '/home/prj/zhengs/caduceuscore/CaduceusCore' 2>/dev/null | grep -E 'simv|p10f3' | grep -v grep | head -5 || echo 'NO_STRAY_PROCESSES'" 2>&1 | tail -5)
  echo "  Stray-process check on sz0001 (repo-scoped): ${STRAY_CHECK}"
  echo ""
  echo "Overall verdict: ${VERDICT}"
  if [ "$VERDICT" = "PASS" ]; then
    echo "  All three key evidences independently reproduced; checkpoint subset"
    echo "  passed the tolerance ladder; sha256 manifest consistent."
  else
    echo "  One or more reproductions failed or the manifest check failed — see above."
  fi
} > "$F3_EVID"
EVIDENCE_WRITTEN=1

log "F3 evidence written: ${F3_EVID}"
cat "$F3_EVID"

echo ""
echo "============================================================"
echo "[P10 F3 MANUAL QA] ${VERDICT}"
echo "  DMA todo-5      : $([ "$DMA_OK" = "1" ] && echo PASS || echo FAIL)"
echo "  PERF-06 todo-9  : $([ "$PERF06_OK" = "1" ] && echo PASS || echo FAIL)"
echo "  Ibex todo-13    : $([ "$IBEX_OK" = "1" ] && echo PASS || echo FAIL)"
echo "  manifest        : ${MANIFEST_STATUS}"
echo "  evidence        : ${F3_EVID}"
echo "============================================================"
[ "$VERDICT" = "PASS" ] && exit 0 || exit 1
